*=============================================================================
* File      : codelists.gms
* Author    : mihaly.himics@ec.europa.eu
* Version   : 1.0
* Date      : 11/18/2011 11:53:49 AM
* Changed   : 11/18/2011 11:56:18 AM
* Changed by: mihaly.himics@ec.europa.eu
* Remarks   :
$ontext
               containing Aglink codeslists with explanations
               should contain the full code lists derived from the data file
$offtext
*=============================================================================

sets
    countries
    commodities
    attributes
    aglinkYears
    tuple(countries, attributes, commodities)
;


parameter    DATAOUT(countries, attributes, commodities, aglinkYears);

$load  countries commodities attributes aglinkYears tuple DATAOUT
$gdxin


execute_unload "temp.gdx" ;


* 
*
*   ---    read in Aglink set definitions from the new GAMS verison of Aglink
* 
$include 'mainsets_MTO2019.gms'




*
*   ---    'Regions and Regional aggregates in Aglink-Cosimo '
* 
alias(AGLINKRegions1, CCC);


*
*   ---    'Aglink-Cosimo variables '
* 
alias(aglinkCols1,MMM); 


*
*   ---    'Aglink-Cosimo commodities '
* 
alias(aglinkRows1, PPP);



$exit

*_ original codes should be checked after every major update of Aglink

*Taken from 'aglink2017OECD_sets.gms'
set aglinkRegions1 /

ARG      "Argentina"
AUS      "Australia"
BRA      "Brazil"
CAN      "Canada"
CHL      "Chile"
CHN      "China"
NMS      "EU New Member States"
E15      "European Union 15"
EUN      "European Union 28"
JPN      "Japan"
MEX      "Mexico"
NZL      "New Zealand"
NOR      "Norway"
RUS      "Russia"
CHE      "Switzerland"
USA      "United States of America"
AGO      "Angola"
BFA      "Burkina Faso"
BGD      "Bangladesh"
CIV      "Côte d'Ivoire"
CMR      "Cameroon"
COD      "Democratic Republic of the Congo"
COG      "Congo"
COL      "Colombia"
DZA      "Algeria"
EGY      "Egypt"
ETH      "Ethiopia"
GAB      "Gabon"
GHA      "Ghana"
HTI      "Haiti"
IDN      "Indonesia"
IND      "India"
IRN      "Iran (Islamic Republic of)"
IRQ      "Iraq"
ISR      "Israel"
KAZ      "Kazakhstan"
KEN      "Kenya"
KHM      "Cambodia"
KOR      "Korea"
LAO      "Lao People's Democratic Republic"
LBN      "Lebanon"
LBY      "Libyan Arab Jamahiriya"
MAR      "Morocco"
MDG      "Madagascar"
MLI      "Mali"
MMR      "Myanmar"
MOZ      "Mozambique"
MRT      "Mauritania"
MWI      "Malawi"
MYS      "Malaysia"
NGA      "Nigeria"
PAK      "Pakistan"
PER      "Peru"
PHL      "Philippines"
PRY      "Paraguay"
RWA      "Rwanda"
SAU      "Saudi Arabia"
SDN      "Sudan"
SEN      "Senegal"
SOM      "Somalia"
TCD      "Chad"
THA      "Thailand"
TUN      "Tunisia"
TUR      "Turkey"
TZA      "United Republic of Tanzania"
UGA      "Uganda"
UKR      "Ukraine"
URY      "Uruguay"
VNM      "Viet Nam"
YEM      "Yemen"
ZAF      "South Africa"
ZMB      "Zambia"
ZWE      "Zimbabwe"
AF1      "Other Subsaharan Africa"
AF2      "Other LDC Subsaharan Africa"
AS2      "Other LDC Asia"
ASA      "Other Asia"
ASD      "Other Asia Developed"
EUE      "Other Eastern Europe"
EUW      "Other Western Europe"
NRE      "Other Middle East"
OCE      "Other Oceania"
OCL      "LDC Oceania"
SAC      "Other South America & Caribbean"

WLD
ACP
/;

set        aglinkCols1 /

'QP..SEC'        'Second generation biofuel production'

* New codes in 2012
'SU'             'Used for sugar'
'BD'             'Biofuel var {only USA}'
'EX..PP'         'Export elasticity'
'IM..PP'         'Import elasticity'
'EXM..PP'        'Export elasticity'
'IMM..PP'        'Import elasticity'
'FE..FHA'        'Aquaculture feed'
'SU..SH'         'Sugar share'
'IM..SHRATL'     'Used for CHN'

'IM..SHREUN'     'Used for CHN'
'IM..SHRPAC'     'Used for CHN'
'EX..SH'         'Used for MOZ'
'IM..OTH'        'other imports'
'BD..ROV'        'Used for USA'
'CG..ROV'        'Used for USA'
'PP..BD..ratio'  'Ratio ethanol and CG (used for USA)'
'NAGR..SHR'      'Used for USA'
'PP..ET..ratio'  'Ratio ethanol and CG (used for USA)'
'PP..ET..TRDratio'   'Used for USA'
'IM..OADV'       'other advanced imports'
'QCS..FFV..EXO'  'Used for USA'
'BD-ADJ'         'biodiesel biofuel mandate in USA'
'BD..ROV..MAX'   'Maximum of possible rollover connected to last years capacity (used for USA)'
'BD..ROV..ratio' 'Ratio that drives the ethanol rollover function (used for USA)'
'BME..ADJ'       'Used for USA'
'BME..BDSH'      'Share of BME used in biodiesiel;% (used for USA)'
'CG..ROV..MAX'   'Maximum of possible rollover connected to last years capacity (used for USA)'
'CG..ROV..ratio' 'Ratio that drives the ethanol rollover function (used for USA)'
'OADV'           'other advanced supported by EISA RFS (used for USA)'
'TOT..ADJ'       'total biofuel mandate in USA (adjusted for anticipated reduction'
'TOT..EFF'       'Used for USA'
'WAIVER'         'Total biofuel waiver (used for USA)'
'PP..BD..TRDratio' 'Used for USA'


* newly introduced codes (2011)
'PP..ET'          'producer price -- commodity for ethanol production'
'MAR..ET'         'margin -- commodity for ethanol production'

'PP..WHO'         'prob: producer price for whole poultry'
'AWU'    'annual work unit'
'DEP'    'Depriciation (EU income module)'
'DIE..EFF'        'conversion between energy diesel and gasoline'
'DP..FIX'         'fixed direct payment by area (Japan rice)'
'DP..VAR'         'variable direct payment by area (Japan rice)'
'DQ..CB' 'calibration quantity (USA)'
'ENPI'   'Energy Price Index (EU income module)'
'EPI..BUDGET'     'Payment equivalent affecting inventories -- budget'
'EX..CB' 'exports calibration quantity (USA)'
'EX..EUN'         'export to EUN (corn gluten feed -- from USA)'
'EX..PAC..SHR'    'export share of pacific market'
'EX..SUBLIM'      'Subsidised export limit'
'EX..SUBOE'       'other subsidized exports (USA)'
'EX..WTO'         'export subsidy quantity limit'
'EXM..SUB'        'export subsidised of meat'
'EXM..SUBLIM'     'Subsidized export limit (for meat)'
'EXM..UNS'        'export unsubsidised of meat'
'FIN'    'Nominal factor income (EU income module)'
'FIN..AWU'        'Nominal factor income per Annual Work Unit (EU income module)'
'FIR'    'Real factor income (EU income module)'
'FIR..AWU'        'Real factor income per Annual Work Unit (EU income module)'
'FO..SHR'         'share of food use'
'GDPD..KAZ'       'GDPD copy for the Kasachstan model'
'GDPD..USA'       'GDPD copy for the US model'
'GVA'    'gross value added'
'IC'     'input cost'
'IC..ENFR'        'input cost energy and fertilizer'
'IC..FEED'        'input cost feed'
'IC..OTH'         'input cost other'
'IC..SEED'        'input cost seeds'
'IM..CXL'         'Import within CXL trq'
'IM..REX'         'prob: Special dairy import quantities in the US'
'IMP..ITQ'        'Import price calculation inside tariff qouta'
'IMP..OTQ'        'Import price calculation outside tariff quota'
'IND..P' 'Price index (EU income module)'
'IND..Q' 'Quantity index (EU income module)'
'IND..V' 'Value index (EU income module)'
'INS'    'Input subsidy'
'LSP'    'Lower stabilisation price (beef japan)'
'MIP'    'approximate effective minimum import price'
'NQT'    'Non-quota'
'NQT..EXSHR'      'Share of export outside quota'
'NVA'    'Net value added (EU income module)'
'PMA..ARG'        'PMA copy for the Argentine model'
'PP..NQT'         'Non-quota producer price for sugar beet'
'PP..USA'         'USA special price (marginal use)'
'QC..EFF'         'energy equivalent production - effective'
'QC..fuel'        'Share in total fuel consumption'
'QC..LBLD'        'Consumption in low blends'
'QCS..CALC'       'Consumption share calculation for biofuels'
'QCS..SEC'        'Consumption share calculation for biofuels (second generation)'
'QP..BV' 'share of beef in ruminants'
'QP..PK' 'share of pork in non-ruminants'
'QP..PT' 'share of poultry in non-ruminants'
'QP..RI' 'ET produced from rice (Japan)'
'QP..SH' 'share of sheep and goat in ruminants'
'RP'     'reference price'
'SAP..DF'         'Average single farm payment -- decoupling factor'
'SAP..HD'         'Average single farm payment -- per head'
'SFP'    'single farm payment'
'SFP..CF'         'Singe farm payment related'
'SGP'    'maximum special safeguard price'
'SH..NAGR'        'Share -- produced from non-agricultural'
'SP..TN' 'purchase price -- dairy price support programs'
'SP..TRG'         'domestic policy support ratio trigger'
'ST..CF' 'Carry-forward stock of non-quota sugar'
'SUB'    'subsidies'
'SUBC'   'subsidies coupled'
'SUBD'   'subsidies decoupled'
'TSP..LIM'        'specific tariff limit'
'VP'     'value of production'
'VP..AGL'         'value of production aglink'
'VP..NAGL'        'value of production non-aglink commodities'
'VP..VEGAG'       '?? Value of production of what?'
'VST..PRST'       'stock change of private stocks'
'XP..KAZ'         'exchange rate Kazakhstan (special)'
'XR..ARG'         'exchange rate Argentina (special)'
'XR..USA'         'exchange rate USA (special)'


* codes without changes -----------------------------
'IM..SHR'         'Import share (SUW)'
'BF'     'Biofuel use'
'BME'    'Biomass for ethanol'
'CG'     'Coarse grains'
'CR'     'Crush'
'FE'     'Feed'
'HFCS'   'High fructose corn sirup'
'NFS'    'Non fat solids milk {new}'
'RFS'               'renewable fuel standard'
'PM'     'PM'
'RES'    'residual'
'SWG'    'SWG'
'AC..ASR'         'ACRE program'
'AC..BFR'         'ACRE program'
'AC..CI' 'ACRE program'
'AC..PG' 'ACRE program'
'AC..PR' 'ACRE program'
'AC..PYT'         'ACRE program'
'AC..SBR'         'ACRE program'
'AC..SPR'         'ACRE program'
'AC..TOT'         'ACRE program'
'AC-YLD'         'ACRE program'
'ADJ'    'Adjustment factor'
'AH'     'Area harvested'
'AH..AC' 'Area harvested'
'AH..AC..PCT'     'Area harvested'
'AH..ADJ'         'Area harvested'
'AH..AGR'         'Area harvested'
'AH..ETR'         'Area harvested'
'AH..NTH'         'Area harvested'
'AH..SHR'         'Area harvested'
'AH..STH'         'Area harvested'
'AHT'    'Total allocatable crop area'
'AP'     'Area planted'
'AP..HA' 'AP..HA'
'APM'    'Milk assumed processing margin and other adjustment'
'AU'     'Alternative usage'
'BF..BD..CONV'    'Biofuel use'
'BF..ET' 'Biofuel use'
'BF..ET..CONV'    'Biofuel use'
'BF..SHR'         'Biofuel use'
'CAL'    'Calories'
'CAL..OTH'        'Calories'
'CC'     'Coefficients'
'CC..LOGA'        'Coefficients'
'CC..LOGB'        'Coefficients'
'CCP'    'Counter-cyclical payments'
'CCP..COEF'       'Counter-cyclical payments'
'CCP..PYD'        'Counter-cyclical payments'
'CCP..TOT'        'Counter-cyclical payments'
'CG..LOGA'        'Coarse grains'
'CG..LOGB'        'Coarse grains'
'CG..MAX'         'Coarse grains'
'CI'     'Cow inventory'
'CI..NQT'         'Cow inventory non-quota'
'COST'   'Production cost'
'CP'     'Consumer price'
'CP..GAS'         'Consumer price'
'CP..SPR'         'Consumer price'
'CPCI'   'Commodity production cost index'
'CPCI..SHE'       'Commodity production cost index'
'CPCI..SHEN'      'Commodity production cost index'
'CPCI..SHFT'      'Commodity production cost index'
'CPCI..SHNT'      'Commodity production cost index'
'CPCI..SHR'       'Commodity production cost index'
'CPCI..SHSD'      'Commodity production cost index'
'CPCI..SHTR'      'Commodity production cost index'
'CPI'    'Consumer price index'
'CRMAR'  'Crush margin'
'CS'     'Consumer subsidy'
'CS..ASTN'        'Consumer subsidy'
'CS..TN' 'Consumer subsidy'
'CVD'    'Countervail duty'
'CW'     'Carcass weight {wrong - Common wheat}'
'DEL'    'Deliveries milk'
'DEL..QT'         'Milk quota'
'DF'     'Decoupling factor'
'DP'     'Direct payments'
'DP..CG' 'Direct payments'
'DP..KG' 'Direct payments'
'DP..ME' 'Direct payments'
'DP..MOL'         'Direct payments'
'DP..QP' 'Direct payments'
'DP..RES'         'Direct payments'
'DP..SBE'         'Direct payments'
'DP..TN' 'Direct payments'
'DP..VL' 'Direct payments'
'DP..WT' 'Direct payments'
'DPA..HA'         'Direct payments'
'DPF'    'Fixed direct payments'
'DPF..KG'         'Fixed direct payments'
'DPF..PYD'        'Fixed direct payments'
'DPF..TN'         'Fixed direct payments'
'DPF..TOT'        'Fixed direct payments'
'EPA'    'payment per area {new}'
'EPA..DP'         'specific direct payments per area {new}'
'EPD'    'consumption subsidy per ton  {new}'
'EPI'    'payment per head  {new}'
'EPI..CF'         'payment per head  {new}'
'EPI..HD'         'payment per head  {new}'
'EPP'    'Effective producer price'
'EPQ'    'payment (livestock) per ton of product  {new}'
'EPY'    'payment (crops) per ton of product  {new}'
'ESP'    'Effective support price'
'EX'     'Exports'
'EX..ACP'         'Exports'
'EX..AID'         'Exports'
'EX..MEX'         'Exports'
'EX..OTH'         'Exports'
'EX..PAC'         'Exports'
'EX..PRO'         'Exports'
'EX..PRO..CAN'    'Exports'
'EX..S'  'Exports'
'EX..SHR'         'Exports'
'EX..SUB'         'Exports'
'EX..SUB..LIM'    'Exports'
'EX..SUB..LIM..VAL'        'Exports'
'EX..SUBLB'       'Exports'
'EX..SUBUB'       'Exports'
'EX..T'  'Exports'
'EX..TAS..WEUN'   'Exports'
'EX..TC..EU'      'Exports'
'EX..UNS'         'Exports'
'EX..USA'         'Exports'
'EX..WEUN'        'Exports'
'EX..WTOFY'       'Exports'
'EX..WUSA'        'Exports'
'EXL'    'Exports live'
'EXL..USA'        'Exports live'
'EXM'    'Exports meat'
'EXM..USA'        'Exports meat'
'EXP'    'Export price (border price in domestic currency)'
'FAD'    'FAD'
'FAT'    'Butterfat content of milk'
'FE..CG' 'Feed'
'FE..NR..BL'      'Feed'
'FE..NR..CG'      'Feed'
'FE..NR..OM'      'Feed'
'FE..NR..PM'      'Feed'
'FE..NR..PN'      'Feed'
'FE..OM' 'Feed'
'FE..PM' 'Feed'
'FE..PN' 'Feed'
'FE..RU..BL'      'Feed'
'FE..RU..CG'      'Feed'
'FE..RU..OM'      'Feed'
'FE..RU..PM'      'Feed'
'FE..RU..PN'      'Feed'
'FE..SHR'         'Feed'
'FE..TOT'         'Feed'
'FECI'   'Feed cost index'
'FECI..NR'        'Feed cost index'
'FEEXP'  'Feed expenditure'
'FEEXP..SHR'      'Feed expenditure'
'FM..DF' 'Fluid milk DF'
'FO'     'Food; waste and seed'
'FO..ADJ'         'Food; waste and seed'
'FO..IM' 'Food; waste and seed'
'FOCI'   'Food cost index'
'FOE'    'Food expenditure'
'FSB'    'FSB'
'FSV..WT'         'FSV..WT'
'FU'     'On-farm use'
'GDPD'   'GDP deflator'
'GDPD..2000'      'GDP deflator'
'GDPD..2002'      'GDP deflator'
'GDPD..2005'      'GDP deflator'
'GDPD..2006'      'GDP deflator'
'GDPD..2007'      'GDP deflator'
'GDPD..2008'      'GDP deflator'
'GDPD..AFL'       'GDP deflator'
'GDPD..AFN'       'GDP deflator'
'GDPD..AFS'       'GDP deflator'
'GDPD..ARG'       'GDP deflator'
'GDPD..ASA'       'GDP deflator'
'GDPD..ASD'       'GDP deflator'
'GDPD..ASL'       'GDP deflator'
'GDPD..AUS'       'GDP deflator'
'GDPD..BGD'       'GDP deflator'
'GDPD..BRA'       'GDP deflator'
'GDPD..CAN'       'GDP deflator'
'GDPD..CHL'       'GDP deflator'
'GDPD..CHN'       'GDP deflator'
'GDPD..COL'       'GDP deflator'
'GDPD..DZA'       'GDP deflator'
'GDPD..EUN'       'GDP deflator'
'GDPD..EGY'       'GDP deflator'
'GDPD..ETH'       'GDP deflator'
'GDPD..EUE'       'GDP deflator'
'GDPD..GHA'       'GDP deflator'
'GDPD..IDN'       'GDP deflator'
'GDPD..IND'       'GDP deflator'
'GDPD..IRN'       'GDP deflator'
'GDPD..JPN'       'GDP deflator'
'GDPD..KOR'       'GDP deflator'
'GDPD..MEX'       'GDP deflator'
'GDPD..MLE'       'GDP deflator'
'GDPD..MOZ'       'GDP deflator'
'GDPD..MYS'       'GDP deflator'
'GDPD..NGA'       'GDP deflator'
'GDPD..NZL'       'GDP deflator'
'GDPD..PAK'       'GDP deflator'
'GDPD..PER'       'GDP deflator'
'GDPD..PHL'       'GDP deflator'
'GDPD..PRY'       'GDP deflator'
'GDPD..RUS'       'GDP deflator'
'GDPD..SAC'       'GDP deflator'
'GDPD..SAU'       'GDP deflator'
'GDPD..SDN'       'GDP deflator'
'GDPD..THA'       'GDP deflator'
'GDPD..TUR'       'GDP deflator'
'GDPD..TZA'       'GDP deflator'
'GDPD..UKR'       'GDP deflator'
'GDPD..URY'       'GDP deflator'
'GDPD..VNM'       'GDP deflator'
'GDPD..ZAF'       'GDP deflator'
'GDPD..ZMB'       'GDP deflator'
'GDPI'   'GDP index'
'IM'     'Imports'
'IM..ACP'         'Imports'
'IM..ADJ'         'Imports'
'IM..BAL'         'Imports'
'IM..EBA'         'Imports'
'IM..FROMBRA'     'Imports'
'IM..MAR'         'Imports'
'IM..OQ' 'Imports'
'IM..PRO'         'Imports'
'IM..PRO..CAN'    'Imports'
'IM..SUP'         'Imports'
'IM..TMAR'        'Imports'
'IM..WBRA'        'Imports'
'IML'    'Imports live'
'IMM'    'Imports meat'
'IMM..HQ'         'Imports meat'
'IMM..LQ'         'Imports meat'
'IMP'    'Import price (border price in domestic currency)'
'IMP..ADJ'        'Import price (border price in domestic currency)'
'IMP..HQ'         'Import price (border price in domestic currency)'
'INV'    'Rural credit'
'IST'    'Intervention stocks'
'LEVY'   'Levy'
'LI'     'Livestock inventory'
'LI..OTH'         'Livestock inventory'
'LR'     'Loan rate'
'LR..AC' 'Loan rate'
'LR..TN' 'Loan rate'
'LR..TNQR'        'Loan rate'
'LRFIX'  'Dummy for fixed loan rate assumption'
'LRQR'   'Dummy for questionnaire-based loan rate assumption'
'MAR'    'Margin'
'MAR..EXO'        'Margin'
'MBD'    'Biof variable  for cosimo countries'

'MLP..AC'         'Marketing loan benefits AC'
'MLP..AV'         'Marketing loan benefits AV'
'MLP..TN'         'Marketing loan benefits TN'
'MLP..TOT'        'Marketing loan benefits TOT'
'MOD'    'Modulation factor'
'MOL..LOGA'       'MOL..LOGA'
'MOL..LOGB'       'MOL..LOGB'
'MP..BRA'         'Specific market or product price'
'MP..GAS'         'Specific market or product price'
'MP..SPR'         'Specific market or product price'
'MSP'    'Minimum support price'
'MUP'    'Mark-up'
'NC..BME'         'Net production cost'
'NC..CG' 'Net production cost'
'NC..CG..CC'      'Net production cost'
'NC..CG..OC'      'Net production cost'
'NC..CG..OIL'     'Net production cost'
'NC..CG..OILC'    'Net production cost'
'NC..MOL'         'Net production cost'
'NC..MOL..CC'     'Net production cost'
'NC..MOL..OC'     'Net production cost'
'NC..MOL..OIL'    'Net production cost'
'NC..MOL..OILC'   'Net production cost'
'NC..RES'         'Net production cost'
'NC..SBE'         'Net production cost'
'NC..SBE..CC'     'Net production cost'
'NC..SBE..OC'     'Net production cost'
'NC..SBE..OIL'    'Net production cost'
'NC..SBE..OILC'   'Net production cost'
'NC..VL' 'Net production cost'
'NC..VL..CC'      'Net production cost'
'NC..VL..OC'      'Net production cost'
'NC..VL..OIL'     'Net production cost'
'NC..VL..OILC'    'Net production cost'
'NC..WT' 'Net production cost'
'NC..WT..CC'      'Net production cost'
'NC..WT..OC'      'Net production cost'
'NC..WT..OIL'     'Net production cost'
'NC..WT..OILC'    'Net production cost'
'NT'     'Trade balance'
'NT..ATL'         'Trade balance'
'NT..FMD'         'Trade balance'
'NT..OCA'         'Trade balance'
'NT..PAC'         'Trade balance'
'NT..WCAN'        'Trade balance'
'NT..WCOL'        'Trade balance'
'NT..WUSA'        'Trade balance'
'OAQ..SBE'        'Overall allotment quantity'
'OAQ..SCA'        'Overall allotment quantity'
'OU'     'Other use'
'PAH'    'PAH'
'PAH..PCT'        'PAH..PCT'
'PC'     '?? {only USA biofuels}'
'PMA'    'PMA'
'POP'    'Population'
'PP'     'Weighted average or Producer price'
'PP..1999'        'Producer price'
'PP..2004'        'Producer price'
'PP..2005'        'Producer price'
'PP..2006'        'Producer price'
'PP..2007'        'Producer price'
'PP..ARG'         'Producer price'
'PP..AUS'         'Producer price'
'PP..BL' 'Producer price'
'PP..BME'         'Producer price'
'PP..BR' 'Producer price'
'PP..CAN'         'Producer price'
'PP..CHN'         'Producer price'
'PP..CWB'         'Producer price'
'PP..EUN'         'Producer price'
'PP..FAT'         'Producer price'
'PP..FM' 'Producer price'
'PP..IM' 'Producer price'
'PP..IM..SM'      'Producer price'
'PP..JPN'         'Producer price'
'PP..KOR'         'Producer price'
'PP..LIP'         'Producer price'
'PP..MEX'         'Producer price'
'PP..NFS'         'Producer price'
'PP..NR..BL'      'Producer price'
'PP..NTH'         'Producer price'
'PP..NZL'         'Producer price'
'PP..OADV'        'Producer price'
'PP..PRAT'        'Producer price'
'PP..RU..BL'      'Producer price'
'PP..SM' 'Producer price'
'PP..STH'         'Producer price'
'PP..VAN'         'Producer price'
'PR..DIE'         'Protein feed {only CHN}'
'PR..GAS'         'Protein feed {only CHN}'
'PREM..FFV'       'Premium'
'PREM..GAS'       'Premium'
'PRST'   'Private stocks'
'PRT..DF'         'PRT..DF'
'PRT..HD'         'PRT..HD'
'QC'     'Consumption'
'QC..ACP'         'Consumption'
'QC..CG' 'Consumption'
'QC..FM' 'Consumption'
'QC..NR..BL'      'Consumption'
'QC..OADV'        'Consumption'
'QC..RU..BL'      'Consumption'
'QCS'    'Consumption share {mainly biof}'
'QCS..ADD'        'Consumption share {mainly biof}'
'QCS..ADDM'       'Consumption share {mainly biof}'
'QCS..EFF'        'Consumption share {mainly biof}'
'QCS..ETV'        'Consumption share {mainly biof}'
'QCS..FFV'        'Consumption share {mainly biof}'
'QCS..HBLD'       'Consumption share {mainly biof}'
'QCS..LBLD'       'Consumption share {mainly biof}'
'QCS..LBLD..EQ'   'Consumption share {mainly biof}'
'QCS..LBLD2'      'Consumption share {mainly biof}'
'QCS..LIMIT'      'Consumption share {mainly biof}'
'QCS..NM'         'Consumption share {mainly biof}'
'QCS..OBL'        'Consumption share {mainly biof}'
'QCS..OBL..TOT'   'Consumption share {mainly biof}'
'QD'     'Government domestic use'
'QP'     'Production'
'QP..ACP'         'Production'

*Renamed in 2012 Aglinked baseline (EUN_BD_QP-SEC + EUN_BD_QP-RES =  EUN_BD_QP-BMD) (pavel)
*QP-SEC is second generation biodiesel and QP-RES is biodiesel from waste oil
*'QP-BMD'         'Production from biomass for diesel'

'QP..BME'         'Production from biomass for ethanol'
'QP..CG' 'Production from coarse grains'
'QP..CG..CONV'    'Production'
'QP..CG..VAL'     'Production'
'QP..DS' 'Production'
'QP..DY' 'Production from dairy'
'QP..ETD'         'Production'
'QP..ETR'         'Production'
'QP..ETR..SH..CG' 'Production'
'QP..ETR..SH..WT' 'Production'
'QP..IM' 'Production'
'QP..JA' 'Production from jatropha'
'QP..MOL'         'Production from molasse'
'QP..MOL..CONV'   'Production'
'QP..MOL..VAL'    'Production'
'QP..NAGR'        'Production from Non-agricultural sources'
'QP..ND' 'Production'
'QP..NQT'         'Production'
'QP..OTH'         'Production from ohers'
'QP..OTHER'       'Production'
'QP..RES'         'Production from residual'
'QP..RT' 'Production from roots and tubers'
'QP..RT..CONV'    'Production'
'QP..SBE'         'Production from sugar beet'
'QP..SBE..CONV'   'Production'
'QP..SBE..VAL'    'Production'
'QP..SCA'         'Production from sugar cane'
'QP..SCA..CONV'   'Production'
'QP..SU' 'Production from sugar'
'QP..T'  'Production'
'QP..VL' 'Production from vegetable oil'
'QP..VL..VAL'     'Production'
'QP..WT' 'Production from wheat'
'QP..WT..CONV'    'Production'
'QP..WT..VAL'     'Production'
'QPC..CG'         'Production capacity'
'QPC..CGEQ'       'Production capacity'
'QPC..MOL'        'Production capacity for molasse'
'QPC..SBE'        'Production capacity for sugar beet'
'QPC..VL'         'Production capacity for vegetable oil'
'QPC..WT'         'Production capacity for wheat'
'QPR..CG'         'Capacity use rate for coarse grains'
'QPR..MOL'        'Capacity use rate for molasse'
'QPR..SBE'        'Capacity use rate for sugar beet'
'QPR..VL'         'Capacity use rate for vegetable oil'
'QPR..WT'         'Capacity use rate for wheat'
'QPRL..CG'        'Lower bound for use rate'
'QPRL..MOL'       'Lower bound for use rate'
'QPRL..SBE'       'Lower bound for use rate'
'QPRL..VL'        'Lower bound for use rate'
'QPRL..WT'        'Lower bound for use rate'
'QPRU..CG'        'Upper bound for use rate'
'QPRU..MOL'       'Upper bound for use rate'
'QPRU..SBE'       'Upper bound for use rate'
'QPRU..VL'        'Upper bound for use rate'
'QPRU..WT'        'Upper bound for use rate'
'QPS'    'Slaughter production'
'QT'     'Quota'
'QT..USA'         'Quota'
'REFMAR' 'Refining margin'
'RET'    'Returns per head'
'REV'    'Revenue from imports'
'RH'     'Returns per hectare'
'RH..CG' 'Returns per hectare'
'RH..E'  'Returns per hectare'
'RH..NTH'         'Returns per hectare'
'RH..STH'         'Returns per hectare'
'RH..W'  'Returns per hectare'
'RH..WT' 'Returns per hectare'
'ROR..CG'         'Profitability indicator'
'ROR..MOL'        'Profitability indicator'
'ROR..SBE'        'Profitability indicator'
'ROR..VL'         'Profitability indicator'
'ROR..WT'         'Profitability indicator'
'RSP'    'Resale price'
'RV'     'RV'
'RV..ET' 'RV..ET'
'SBE..LOGA'       'SBE..LOGA'
'SBE..LOGB'       'SBE..LOGB'
'SD'     'Statistical difference {closes world market balance}'
'SFP..DF'         'Single farm payment'
'SFP..HD'         'Single farm payment'
'SH..CG' 'SH..CG'
'SH..ETD'         'SH..ETD'
'SH..ETR'         'SH..ETR'
'SH..JA' 'SH..JA'
'SH..MOL'         'SH..MOL'
'SH..RT' 'SH..RT'
'SH..SCA'         'SH..SCA'
'SH..VL' 'SH..VL'
'SH..WT' 'SH..WT'
'SHR'    'Share'
'SHR..NR'         'Share'
'SHR..NR..CG'     'Share'
'SHR..NR..OM'     'Share'
'SHR..NR..PM'     'Share'
'SHR..NR..PN'     'Share'
'SHR..RU'         'Share'
'SHR..RU..CG'     'Share'
'SHR..RU..OM'     'Share'
'SHR..RU..PM'     'Share'
'SHR..RU..PN'     'Share'
'SHR..VL'         'Share'
'SIP'    'Standard import price'
'SP'     'Support price'
'SPE'    'SPE'
'SPV'    'SPV'
'ST'     'Ending stocks'
'ST..ACP'         'Ending stocks'
'ST1'    'Intermediate stock calculation'
'ST2'    'Intermediate stock calculation'
'TARA'   'Applied tariff in ad valorem equivalent {not used anymore}'
'TARS'   'Specific tariff {not used anymore}'
'TAS'    'Specific tariff'
'TAV'    'Ad valorem tariff'
'TAV..HQ..OQS'    'Ad valorem tariff'
'TAV..IQS'        'Ad valorem tariff'
'TAV..NQS'        'Ad valorem tariff'
'TAV..OQS'        'Ad valorem tariff'
'TAVE'   'Export tariffs {new}'
'TAVI'   'Import tariffs {new}'
'TAVI..HQ'        'Import tariffs {new}'
'TAVI..HQ..IQS'   'Import tariffs {new}'
'TAX'    'Tax'
'TAX..CRD'        'Tax'
'TC'     'Transport costs'
'TC..NTH'         'Transport costs'
'TCE'    'Transport costs exports'
'TCI'    'Transport costs imports'
'TOT'    'TOT'
'TOT..MAX'        'TOT..MAX'
'TP'     'Target price'
'TP..TN' 'Target price'
'TRC'    'Transport costs'
'TRC..CAN'        'Transport costs'
'TRG'    'Transport costs'
'TRQ'    'Tariff rate quota'
'TRQ..CBISHR'     'Tariff rate quota'
'TRQ..HQ'         'Tariff rate quota'
'TRQ..MEX'        'Tariff rate quota'
'TRQ..WUSA'       'Tariff rate quota'
'TSP'    'Specific tariff {new}'
'TSP..HQ..OQS'    'Specific tariff {new}'
'TSP..IQS'        'Specific tariff {new}'
'TSP..OQS'        'Specific tariff {new}'
'TVE'    'Variable transport costs exports {related to oil prices}'
'TVI'    'Variable transport costs imports'
'VAT'    'Value added tax'
'VL..LOGA'        'VL..LOGA'
'VL..LOGB'        'VL..LOGB'
'VNC..CG'         'Variable net cost'
'VNC..MOL'        'Variable net cost'
'VNC..SBE'        'Variable net cost'
'VNC..VL'         'Variable net cost'
'VNC..WT'         'Variable net cost'
'VST'    'Variation in stocks'
'WAS'    'Waste or statistical difference'
'WT..LOGA'        'WT..LOGA'
'WT..LOGB'        'WT..LOGB'
'XP'     'World price'
'XP..2000'        'World price'
'XP..2005'        'World price'
'XP..2006'        'World price'
'XP..2007'        'World price'
'XP..2008'        'World price'
'XP..AFL'         'World price'
'XP..AFN'         'World price'
'XP..AFS'         'World price'
'XP..ARG'         'World price'
'XP..ASA'         'World price'
'XP..ASD'         'World price'
'XP..ASL'         'World price'
'XP..AUS'         'World price'
'XP..BGD'         'World price'
'XP..BRA'         'World price'
'XP..CAN'         'World price'
'XP..CHL'         'World price'
'XP..CHN'         'World price'
'XP..COL'         'World price'
'XP..DZA'         'World price'
'XP..EUN'         'World price'
'XP..EGY'         'World price'
'XP..ETH'         'World price'
'XP..EUE'         'World price'
'XP..GHA'         'World price'
'XP..IDN'         'World price'
'XP..IND'         'World price'
'XP..IRN'         'World price'
'XP..JPN'         'World price'
'XP..KOR'         'World price'
'XP..MEX'         'World price'
'XP..MLE'         'World price'
'XP..MOZ'         'World price'
'XP..MYS'         'World price'
'XP..NGA'         'World price'
'XP..NZL'         'World price'
'XP..PAK'         'World price'
'XP..PER'         'World price'
'XP..PHL'         'World price'
'XP..PRY'         'World price'
'XP..RUS'         'World price'
'XP..SAC'         'World price'
'XP..SAU'         'World price'
'XP..SDN'         'World price'
'XP..THA'         'World price'
'XP..TUR'         'World price'
'XP..TZA'         'World price'
'XP..UKR'         'World price'
'XP..URY'         'World price'
'XP..USA'         'World price'
'XP..VNM'         'World price'
'XP..ZAF'         'World price'
'XP..ZMB'         'World price'
'XR'     'Exchange rate'
'XR..2000'        'Exchange rate'
'XR..2005'        'Exchange rate'
'XR..2006'        'Exchange rate'
'XR..2007'        'Exchange rate'
'XR..2008'        'Exchange rate'
'XR..NZL'         'Exchange rate'
'YLD'    'Yield'
'YLD-AVE'        'Yield'
'YLD-AVE-SBE'   'Yield'
'YLD-AVE-SCA'   'Yield'
'YLD-ETD'        'Yield'
'YLD-ETR-CG'    'Yield'
'YLD-ETR-WT'    'Yield'
'YLD-SBE'        'Yield'
'YLD-SCA'        'Yield'


/;



set        aglinkRows1/
* codes not available anymore  (2011)
$ontext
'PR'     'Protein'
'BL'     'Butter oil'
'DY'     'Dairy'
'GC'     'Total grain consuming'
'GR'     'Grain'
'HP'     'High protein'
'INU'    'Inuline'
'SBES'   'Sugar beet {only USA}'
'SCAS'   'Sugar cane {only USA}'
'SWO'    'Other sweetener {only CHN}'
'WS'     'Wheat/Soyabeans'
$offtext

* codes not available anymore  (2012)
*'COP'    'cereals oilseeds and protein crops'
*'CR'     'Cereals'

* newly introduced codes (2011)
'CE'     'Cereals'

* newly introduced codes (2011)
'COP'    'cereals oilseeds and protein crops'
'CRX'    'Other area (residual)'
'ELE'    'Electricity (for input subsidies, only India)'
'FO'     'Forage'
'SET'    'Set aside'
'WAT'    'Water  (for input subsidies, only India)'

* codes without changes -----------------------------
'BF'     'Biofuels  {new}'
'BME'    'Biomass for ethanol  {new}'
'CG'     'Coarse grains'

'FE'     'Feed   {not used}'
'FP'     'Field peas'
'HFCS'   'High fructose corn sirup'
'LA'     'Lamb meat'
'MP'     'Milk powder'
'NFS'    'Non-fat solids in milk {only CAN}'
'PM'     'Protein meal {new}'
'RES'    'Biofuel var {only USA}'
'SWG'    'Other sweetener {only USA and CHN}'
'ADD'    'Additive'
'AG'     'Agriculture'
'BA'     'Barley'
'BD'     'Biodiesel'
'BLD'    'Blend'
'BN'     'Dried beans'
'BP'     'Beet pulpe'
'BT'     'Butter'
'BV'     'Beef and veal  {new}'
'CA'     'Casein'
'CEO'    'Cereals and oilseeds {new}'
'CF'     'Corn gluten feed {called CGF in most regions}'
'CGF'    'Corn gluten feed {called CF for some regions}'
'CH'     'Cheese'
'CK'     'Chicken meat'
'CKB'    'Chicken brown meat'
'CKW'    'Chicken white meat'
'CL'     'Coconut oil  {new}'
'CM'     'Coconut meal  {new}'
'CN'     'Copra  {new}'
'CSE'    'Cottonseed  {new}'
'CSL'    'Cottonseed oil  {new}'
'CSM'    'Cottonseed meal  {new}'
'CT'     'Cotton'
'DDG'    'Dried Distillers Grains'
'DEX'    'Dextrose'
'DIE'    'Diesel'
'EF'     'Energy rich-feed'
'EG'     'Eggs'
'ET'     'Ethanol'
'ETD'    'Ethanol related  {cosimo countries}'
'ETR'    'Ethanol related  {cosimo countries}'
'ETV'    'Ethanol in volume'
'FDP'    'Fresh dairy product'
'FF'     'Flexi-fuels  {only CAN}'
'FFV'    'Flexi-fuels vehicles'
'FH'     'Fish'
'FT'     'Fertiliser'
'GAS'    'Gasoline'
'GL'     'Groundnut oil {new}'
'GLU'    'Glucose'
'GM'     'Groundnut meal {new}'
'GN'     'Groundnuts {new}'
'HY'     'Hay {only US price}'
'JA'     'Jatropha'
'KL'     'Palmkernel oil {new}'
'KM'     'Palmkernel meal {new}'
'MA'     'Maize'
'MD'     'Meat and dairy'
'ME'     'Macroeconomic'
'MK'     'Milk'
'MOL'    'Molasse'
'MT'     'Total meat'
'MU'     'Mutton'
'NR'     'Non-ruminant'
'OBP'    'Other by-products'
'OC'     'Other cereals'
'ODP'    'Other dairy product'
'OFP'    'Milk other fat products {new definition}'
'OIL'    'Crude oil'
'OL'     'Oilseed oils'
'OM'     'Oilseed meals'
'ONP'    'Milk other non-fat products {new}'
'OOS'    'Other oilseeds  {only AUS,MEX and RUS}'
'OP'     'Other poultry meat'
'OS'     'Oilseeds'
'OT'     'Oats'
'OX'     'Other land use {new only EU}'
'PA'     'Pasture'
'PF'     'Field peas'
'PK'     'Pork meat'
'PKL'    'Palm kernels {new}'
'PL'     'Palm oil'
'PN'     'Oilseed meals and field peas   {not used}'
'PO'     'Potatoes'
'PT'     'Poultry meat'
'RFS'    'Biofuel var {only USA}'
'RI'     'Rice'
'RL'     'Rapeseed oil'
'RM'     'Rapeseed meal'
'RP'     'Rapeseed'
'RT'     'Roots and tubers'
'RU'     'Ruminant'
'RY'     'Rye'
'SB'     'Soybeans'
'SBE'    'Sugar beet'
'SC'     'Special crops'
'SCA'    'Sugar Cane'
'SF'     'Sunflower seed'
'SFL'    'Sunflower oil'
'SFM'    'Sunflower meal'
'SH'     'Sheep meat {sheep and goat meat}'
'SL'     'Soybean oil'
'SM'     'Soybean meal'
'SMP'    'Skimmed milk powder'
'SO'     'Sorghum'
'SU'     'Sugar (in raw sugar equivalent)'
'SUMOL'  'Sugar and molasse'
'SUPRO'  'USA imports of sugar through products'
'SUR'    'Raw Sugar (in raw sugar equivalent) {new name}'
'SUW'    'Refined Sugar (in raw sugar equivalent) {new name}'
'SW'     'Sweetener'
'VL'     'Vegetable oils'
'WL'     'Wool'
'WMP'    'Wholemilk powder'
'WT'     'Wheat'
'WTD'    'Durum wheat {only EU}'
'WTS'    'Soft wheat {only EU}'
'WYP'    'Whey powder'
'FM'     'Fishmeal'


/;







*============================   End Of File   ================================
