* Sets created from sets.xlsm file
SET CCC    'Country parent set' /
'USA'	'  United States'
'ARG'	'  Argentina'
'AUS'	'  Australia'
'BRA'	'  Brazil'
'CAN'	'  Canada'
'CHE'	'  Switzerland'
'CHN'	'  China (main)'
'E15'	'  EU-15'
'EUN'	'  European Union'
'JPN'	'  Japan'
'KOR'	'  South Korea'
'MEX'	'  Mexico'
'NMS'	'  New EU memberstates (later than EU15)'
'NOR'	'  Norway'
'NZL'	'  New Zealand'
'RUS'	'  Russia'
'BGD'	'  Bangladesh'
'CHL'	'  Chile'
'COL'	'  Colombia'
'DZA'	'  Algeria'
'EGY'	'  Egypt'
'ETH'	'  Ethiopie'
'EUE'	'  Other East Europe '
'EUW'	'  Other West Europe '
'GHA'	'  Ghana'
'HTI'	'  Haiti'
'IDN'	'  Indonesia'
'IND'	'  India'
'IRN'	'  Iran'
'ISR'	'  Israel'
'KAZ'	'  Kazakhstan'
'MAR'	''
'MOZ'	'  Mozambique'
'MYS'	'  Malaysia'
'NGA'	'  Nigeria'
'PAK'	'  Pakistan'
'PER'	'  Peru'
'PHL'	'  Philippines'
'PRY'	'  Paraguay'
'SAC'	'  Other South America '
'SAU'	'  Saudi Arabia'
'SDN'	'  Sudan '
'THA'	'  Thailand'
'TUR'	'  Turkey'
'TZA'	'  Tanzania'
'UKR'	'  Ukraine'
'URY'	'  Uruguay'
'VNM'	'  Vietnam'
'ZAF'	'  South Africa'
'ZMB'	'  Zambia'
'**possibleCOSIMOAggregates'	''
'AFL'	'  Africa Southern Least Developed'
'AFN'	'  Other North Africa '
'AFS'	'  Other Sub-Saharan Africa  '
'ASA'	'  Other Asia '
'ASD'	'  Other CIS --- Other Asia Developed'
'ASL'	'  LDC - Southern Africa '
'OCE'	'  Other Oceania '
'OCL'	'  Oceania Least Developed  '
'MLE'	'  Middle East '
'AF1'	' Sub saharan Africa countries not modelled explicetly'
'AF2'	' Sub saharan Africa LDC countries not modelled explicetly'
'AS2'	' Asian LDC countries not modelled explicetly'
'NRE'	' Near East countries not modelled explicetly'
'RAF'	' Sub-Saharan Africa'
'RNE'	' Near East and North Africa'
'RLC'	' Latin America and the Caribbean'
'RAP'	' Asia and the Pacific'
'REU'	' Europe and Central Asia'
'**aggregatesusedinthemodel'	''
'WLD'	'  World'
'AGL'	'  Aglink Aggregate'
'COS'	'  Cosimo Aggregate'
'ATL'	'  Atlantic Market'
'PAC'	'  Pacific Market'
'PAC..BV'	'  Pacific Market beef'
'PAC..PK'	'  Pacific Market pork'
'ATL..BV'	'  Atlantik Market beef'
'ATL..PK'	'  Atlantic Market pork'
'**postmodelaggregates'	''
'ENDO'	' Endogeneous model counties'
'DVD'	' DEVELOPED          '
'NAM'	' NORTH AMERICA      '
'WEE'	' WESTERN EUROPE     '
'OCD'	' OCEANIA DEVELOPED  '
'OIN'	' OTHER DEVELOPED    '
'EEE'	' EASTERN EUROPE     '
'DVG'	' DEVELOPING         '
'AFR'	' AFRICA           '
'NAF'	' NORTH AFRICA       '
'SSA'	' SUB SAHARAN AFRICA (without SouthAfrica) '
'*NRE'	' NEAR EAST          '
'LAM'	' LATIN AMER and CARIB '
'ASI'	' ASIA DEVELOPING    '
'OCA'	' OCEANIA DEVELOPING '
'LDC'	' LEAST DEVELOPING   '
'ODV'	' NOT LEAST DEVELOPING'
'OED'	' OECD Aggregate     '
'NOE'	' Non-OECD Aggregate '
'G20'	' G20 nations'
'BRIC'	' BRIC countries'
'BRICS'	' BRICS countries'
'ASE'	'  South-east Asean countries'
'AOS'	' Other sub saharan Africa'
'AOL'	' Cariibean countries'
'LAC'	' Latin Ameraica aggregate'
'POA'	' Other Asia Pasific'
'ASP'	' Asia Pasific'
'AGO'	''
'BFA'	''
'CIV'	''
'CMR'	''
'COD'	''
'COG'	''
'GAB'	''
'IRQ'	''
'KEN'	''
'KHM'	''
'LAO'	''
'LBN'	''
'LBY'	''
'MDG'	''
'MLI'	''
'MMR'	''
'MRT'	''
'MWI'	''
'RWA'	''
'SEN'	''
'SOM'	''
'TCD'	''
'TUN'	''
'UGA'	''
'YEM'	''
'ZWE'	''
'ROW'	'Rest of world'
'GUL     '	''
'JOR     '	''
'MSR     '	''
'ASC     '	''
'NOA'	'North America'
'EUR'	'Europe '
'O34'	'OECD'
'MER'	'Mercosur'
/;
*
SET AGLC(CCC)    'Aglink countries' 
	/'ARG','AUS','BRA','CAN','CHE','CHN','EUN','JPN','KOR','MEX','NOR','NZL','RUS','USA'/;
*
SET EUNC(CCC)    'Members of the European Union' 
	/'E15','NMS'/;
*
SET biofC(CCC)    'biofuel countries of AGLINK' 
	/'ARG','AUS','BRA','CAN','CHN','EUN','JPN','KOR','MEX','NZL','RUS','USA','CHE','NOR','IDN','IND','THA','MYS','COL','PER','CHL','PRY','PHL'/;
*
SET ModAggs(CCC)    'Regional aggregates used in the core model' 
	/'WLD','AGL','COS','PAC','ATL'/;
*
SET COSC(CCC)    'Cosimo regions' 
	/'AFL','AFS','ETH','NGA','ZAF','AFN','DZA','EGY','GUL','IRN','JOR','LBN','LBY','MAR','MSR','SAU','TUN','YEM','CHL','COL','PRY','SAC','ASA','ASL','IDN','IND','MYS','OCE','PAK','PHL','THA','VNM','ASC','EUE','ISR','KAZ','TUR','UKR'/;
*
SET wldAgg1(CCC)    'World as Aglink + Cosimo' 
	/'AGL','COS'/;
*
SET NOAC(CCC)    'North America' 
	/'USA','CAN'/;
*
SET EURC(CCC)    'Europe' 
	/'EUN','RUS','UKR','EUE','CHE','NOR'/;
*
SET LATC(CCC)    'LATIN AMERICA and CARIBBEAN' 
	/'SAC','ARG','BRA','MEX','CHL','COL','PRY'/;
*
SET AFRC(CCC)    'Africa' 
	/'DZA','EGY','TUN','MAR','LBY','AFN','AFS','AFL','ZAF','ETH','NGA','YEM'/;
*
SET ASPC(CCC)    'Asia' 
	/'ASL','GUL','MSR','ASA','KOR','CHN','IND','IDN','IRN','MYS','SAU','PAK','PHL','THA','TUR','VNM','JPN','ISR','JOR','KAZ','LBN','ASC'/;
*
SET OCDC(CCC)    'OCEANIA' 
	/'AUS','NZL','OCE'/;
*
SET DVDC(CCC)    'Developped' 
	/'JPN','ISR','KAZ','ASC','USA','CAN','AUS','NZL','ZAF','EUN','RUS','UKR','EUE','CHE','NOR'/;
*
SET DVGC(CCC)    'Developping' 
	/'DZA','EGY','TUN','MAR','LBY','AFN','AFS','AFL','ETH','NGA','YEM','ASL','GUL','MSR','ASA','OCE','KOR','CHN','IND','IDN','IRN','MYS','SAU','PAK','PHL','THA','TUR','VNM','JOR','LBN','SAC','ARG','BRA','MEX','CHL','COL','PRY'/;
*
SET CntryMt(CCC)    'Country list Mn ton calculation' 
	/'WLD','OED','DVD','DVG'/;
*
SET OECD(CCC)    'Oecd Countries' 
	/'USA','AUS','CAN','CHE','EUN','JPN','KOR','MEX','NOR','NZL','CHL','ISR','TUR'/;
*
SET Wldlist(CCC)    'World list' 
	/'ARG','AUS','BRA','CAN','CHE','CHN','EUN','JPN','KOR','MEX','NOR','NZL','RUS','USA','AFL','AFS','ETH','NGA','ZAF','AFN','DZA','EGY','GUL','IRN','JOR','LBN','LBY','MAR','MSR','SAU','TUN','YEM','CHL','COL','PRY','SAC','ASA','ASL','IDN','IND','MYS','OCE','PAK','PHL','THA','VNM','ASC','EUE','ISR','KAZ','TUR','UKR','OED','NOA','EUR','LAC','AFR','ASP','OCD','DVD','DVG','WLD','LDC','PAC','ATL','E15','BRICS','MER','RNE','PER','SSA'/;
*
SET GHGC(CCC)    'Biofuel countries for GHG calculation' 
	/'ARG','AUS','BRA','CAN','CHE','CHL','CHN','COL','EUN','IDN','IND','JPN','KOR','MEX','MYS','NOR','NZL','PER','PHL','PRY','ROW','RUS','THA','USA'/;
*
SET LDCC(CCC)    'Least developping countries' 
	/'AFL','ASL'/;
*
SET BRICSC(CCC)    'BRICS' 
	/'BRA','ZAF','RUS','IND','CHN'/;
*
SET RNEC(CCC)    'MENA countries' 
	/'AFN','DZA','EGY','GUL','IRN','JOR','LBN','LBY','MAR','MSR','SAU','TUN','YEM'/;
*
SET SSAC(CCC)    'Sub Saharan Africa' 
	/'AFL','AFS','ETH','NGA','ZAF'/;
*
SET regions_map(*,CCC)  'maping between single set elemnts and aggregates' /
'AGL'.('ARG','AUS','BRA','CAN','CHE','CHN','EUN','JPN','KOR','MEX','NOR','NZL','RUS','USA')
*
'EUN'.('E15','NMS')
*
'BIOFC'.('ARG','AUS','BRA','CAN','CHN','EUN','JPN','KOR','MEX','NZL','RUS','USA','CHE','NOR','IDN','IND','THA','MYS','COL','PER','CHL','PRY','PHL')
*
'ModAggs'.('WLD','AGL','COS','PAC','ATL')
*
'COS'.('AFL','AFS','ETH','NGA','ZAF','AFN','DZA','EGY','GUL','IRN','JOR','LBN','LBY','MAR','MSR','SAU','TUN','YEM','CHL','COL','PRY','SAC','ASA','ASL','IDN','IND','MYS','OCE','PAK','PHL','THA','VNM','ASC','EUE','ISR','KAZ','TUR','UKR')
*
'WLD'.('AGL','COS')
*
'NOA'.('USA','CAN')
*
'EUR'.('EUN','RUS','UKR','EUE','CHE','NOR')
*
'LAC'.('SAC','ARG','BRA','MEX','CHL','COL','PRY')
*
'AFR'.('DZA','EGY','TUN','MAR','LBY','AFN','AFS','AFL','ZAF','ETH','NGA','YEM')
*
'ASP'.('ASL','GUL','MSR','ASA','KOR','CHN','IND','IDN','IRN','MYS','SAU','PAK','PHL','THA','TUR','VNM','JPN','ISR','JOR','KAZ','LBN','ASC')
*
'OCD'.('AUS','NZL','OCE')
*
'DVD'.('JPN','ISR','KAZ','ASC','USA','CAN','AUS','NZL','ZAF','EUN','RUS','UKR','EUE','CHE','NOR')
*
'DVG'.('DZA','EGY','TUN','MAR','LBY','AFN','AFS','AFL','ETH','NGA','YEM','ASL','GUL','MSR','ASA','OCE','KOR','CHN','IND','IDN','IRN','MYS','SAU','PAK','PHL','THA','TUR','VNM','JOR','LBN','SAC','ARG','BRA','MEX','CHL','COL','PRY')
*
'CntryMt'.('WLD','OED','DVD','DVG')
*
'OED'.('USA','AUS','CAN','CHE','EUN','JPN','KOR','MEX','NOR','NZL','CHL','ISR','TUR')
*
'WLDLIST'.('ARG','AUS','BRA','CAN','CHE','CHN','EUN','JPN','KOR','MEX','NOR','NZL','RUS','USA','AFL','AFS','ETH','NGA','ZAF','AFN','DZA','EGY','GUL','IRN','JOR','LBN','LBY','MAR','MSR','SAU','TUN','YEM','CHL','COL','PRY','SAC','ASA','ASL','IDN','IND','MYS','OCE','PAK','PHL','THA','VNM','ASC','EUE','ISR','KAZ','TUR','UKR','OED','NOA','EUR','LAC','AFR','ASP','OCD','DVD','DVG','WLD','LDC','PAC','ATL','E15','BRICS','MER','RNE','PER','SSA')
*
'GHGC'.('ARG','AUS','BRA','CAN','CHE','CHL','CHN','COL','EUN','IDN','IND','JPN','KOR','MEX','MYS','NOR','NZL','PER','PHL','PRY','ROW','RUS','THA','USA')
*
'LDC'.('AFL','ASL')
*
'BRICS'.('BRA','ZAF','RUS','IND','CHN')
*
'RNE'.('AFN','DZA','EGY','GUL','IRN','JOR','LBN','LBY','MAR','MSR','SAU','TUN','YEM')
*
'SSA'.('AFL','AFS','ETH','NGA','ZAF')
*
/;
SET PPP    'Product parent set' /
'ADD'	'Additive'
'AG'	''
'AGO'	'Non modelled crop areas'
'AGR'	'Total agricultural area'
'APF'	'All protein feed'
'BA'	'Barley'
'BBP'	''
'BD'	'Biodiesel'
'BF'	'Biofuels'
'BLD'	'Blended'
'BME'	'Biomass'
'BN'	'Beans'
'BP'	'Dried beet pulp'
'BT'	'Butter'
'BV'	'Beef and Veal'
'BYD'	'Backyard production'
'CA'	'Casein'
'CE'	''
'CEB'	'Cereal brans'
'CEO'	'Cereals'
'CG'	'Coarse grains'
'CGF'	'Corn Gluten Feed'
'CH'	'Cheese'
'CK'	'Chicken'
'CKB'	'Chicken brown'
'CKW'	'Chicken white'
'CL'	'Copra (coconut) oil'
'CM'	'Copra (coconut) meal'
'CN'	'Copra (coconut)'
'CR'	'Crop'
'CRP'	'Crops'
'CRX'	'Annual crop not included elsewhere'
'CSE'	'Cotton seed'
'CSL'	'Cotton seed oil'
'CSM'	'Cotton seed meal'
'CT'	'Cotton'
'DDG'	'Dried Distillers Grains'
'DEX'	'Dextrose'
'DIE'	'Diesel'
'DY'	'Dairy'
'EF'	'Energy feed'
'EG'	'Eggs'
'ET'	'Ethanol'
'ETV'	''
'FDP'	'Fresh dairy products'
'FF'	''
'FFV'	'Flexible fuel vehicles'
'FH'	'Fish'
'FHA'	'Fish from aquaculture'
'FM'	'Fish meal'
'FO'	'Fodder crops'
'FP'	'Field peas'
'FST'	'Forest'
'FT'	'Fertilizer'
'GAS'	'Gasoline'
'GL'	'Groundnut oil'
'GLU'	'Glucose'
'GLUDEX'	'Glucose and dextrose'
'GM'	'Groundnut meal'
'GN'	'Groundnut'
'HFCS'	'High fructose corn syrup'
'HPF'	'High protein feed'
'HY'	'Hay'
'JA'	'Jatropha'
'KL'	'Palm kernel oil'
'KM'	'Palm kernel meal'
'LA'	'Lambs'
'LND'	'Total Land'
'LPF'	'Low protein feed'
'MA'	'Maize'
'MBM'	'Meat and bone meal'
'MD'	'Meat and dairy'
'ME'	'Macro variables'
'MK'	'Milk'
'MOL'	'Molasses'
'MOP'	''
'MP'	''
'MPF'	'Medium protein feed'
'MT'	'Meat'
'MU'	'Mutton'
'NAGR'	''
'NAGRD'	''
'NAGRE'	''
'NFS'	'Non-fat solids'
'NR'	'Non ruminants'
'OBP'	'Other by-products'
'OC'	'Other cereals'
'OCG'	'Other coarse grains'
'ODP'	'Other dairy products (ice cream'
'OFP'	'Other dairy product containing fat solids'
'OIL'	'Crude oil'
'OL'	'Oilseed oils'
'OLN'	'Other Land'
'OM'	'Oilseed meals'
'ONP'	'Other dairy product containing non-fat solids'
'OOL'	'Other Oilseed oils'
'OOM'	'Other Oilseed meals'
'OOS'	'Other Oilseeds'
'OP'	'Other poultry'
'OPS'	'Other pulses'
'OS'	'Oilseeds'
'OT'	'Oats'
'OX'	'Land devoted to other than cereals'
'PA'	'Pasture'
'PAF'	'Pasture and Fodder'
'PF'	'Protein feed'
'PHO'	'Unknown'
'PK'	'Pork'
'PKL'	'Palm kernel'
'PL'	'Palm oil'
'PM'	'Total Protein Meal'
'PS'	'Pulses'
'PT'	'Poultry'
'RES'	'Crop residues'
'RFS'	'Renewable fuel standard'
'RI'	'Rice'
'RL'	'Rapeseed oil'
'RM'	'Rapeseed meal'
'RP'	'Rapeseed'
'RT'	'Roots and tubers'
'RU'	'Ruminants'
'RY'	'Rye'
'SB'	'Soybean'
'SBE'	'Sugarbeet'
'SC'	'Special crops production (prairies)'
'SCA'	'Sugarcane'
'SET'	'Set aside'
'SF'	'Sunflower seed'
'SFL'	'Sunflower oil'
'SFM'	'Sunflower meal'
'SH'	'Sheep'
'SL'	'Soybean oil'
'SM'	'Soybean meal'
'SMP'	'Skim milk powder'
'SO'	'Sorghum'
'SU'	'Sugar'
'SUMOL'	'Sugar and molasses'
'SUPRO'	'Product containing sugar'
'SUR'	'Raw sugar'
'SUW'	'White sugar'
'SW'	'Sweetener'
'SWG'	'Sweeteners from cereals'
'URE'	'Urea'
'VL'	'Vegetable oils'
'WL'	'Wool'
'WMP'	'Whole milk powder'
'WT'	'Wheat'
'WTD'	'Durum wheat'
'WTS'	'Soft wheat'
'WYP'	'Whey powder'
'MTW'	'Meat weighted aggregation'
'OVL  '	''
'WLF  '	''
'ECR  '	''
'ARES '	''
'FRES '	''
'MSW  '	''
'OTHW '	''
'BVV'	'Veal'
'FL'	'Fish oil'
'MTT'	'Meat mnemonic for edpba'
'FHC'	'Fish from capture'
'meat'	'total meats'
'rest'	'rest category'
'tot'	'total aggregate'
/;
*
SET pClear(PPP)    'Products with world clearing equations' 
	/'BD','BP','BT','CEB','CGF','CH','CT','DDG','ET','HFCS','MA','MBM','MOL','OCG','OOS','PM','PS','PT','RI','RT','SB','SH','SMP','SUR','SUW','VL','WMP','WT','WYP'/;
*
SET main_crop(PPP)    'Main Crop products' 
	/'CT','MA','OCG','OOS','PS','RI','RT','SB','SBE','SCA','WT'/;
*
SET ntP(PPP)    'Products with nettrade variable' 
	/'BP','BT','BV','CEB','CGF','CH','CT','DDG','EG','MA','MBM','MOL','OCG','OOS','PK','PM','PT','RI','RT','SB','SH','SMP','SU','SUR','SUW','VL','WMP','WT','WYP'/;
*
SET bioF(PPP)    'biouels' 
	/'BD','ET'/;
*
SET fuel(PPP)    'fossil fuels' 
	/'DIE','GAS'/;
*
SET meat(PPP)    'meats' 
	/'BV','PK','PT','SH'/;
*
SET coarsG(PPP)    'coarse grains' 
	/'MA','OCG'/;
*
SET OLOM(PPP)    'Oil seed oils and oil seed meals' 
	/'OL','OM'/;
*
SET pAgg(PPP)    'Products needed for aggregation' 
	/'BD','BP','BT','CA','CEB','CGF','CH','CT','DDG','ET','FT','HFCS','MA','MBM','MOL','OCG','OOS','PM','PS','PT','RI','RT','SB','SH','SMP','SUR','SUW','VL','WMP','WT','WYP','SU','BV','PK','FH','ME','MK','AGO','FST','OLN','AGR','CG','FM','FL','MTT','MT','MTW','SCA','SBE','FDP','EG','PL','FHA','FHC','DY','CE','CRP'/;
*
SET BDSH(PPP)    'products needed for share calculations in GHG' 
	/'PL','SL','RL','SFL','JA','OVL','WLF','ECR','ARES','FRES','MSW','OTHW'/;
*
SET ETSH(PPP)    'products needed for share calculations in GHG' 
	/'SBE','SCA','WT','MA','OCG','MOL','RT','RI','ECR','ARES','FRES','MSW','OTHW'/;
*
SET foodP(PPP)    'food products' 
	/'WT','MA','OCG','RI','SB','OOS','VL','SU','HFCS','FDP','BT','CH','SMP','WMP','CA','BV','PK','PT','SH','RT','FH','FL','WYP','EG','PS'/;
*
SET DY(PPP)    'dairy market products' 
	/'BT','CH','SMP','WMP','FDP','WYP','CA'/;
*
SET CERE(PPP)    'Cereals' 
	/'MA','WT','OCG','RI'/;
*
SET products_map(*,PPP)  'maping between single set elemnts and aggregates' /
'PCLEAR'.('BD','BP','BT','CEB','CGF','CH','CT','DDG','ET','HFCS','MA','MBM','MOL','OCG','OOS','PM','PS','PT','RI','RT','SB','SH','SMP','SUR','SUW','VL','WMP','WT','WYP')
*
'MCR'.('CT','MA','OCG','OOS','PS','RI','RT','SB','SBE','SCA','WT')
*
'NTP'.('BP','BT','BV','CEB','CGF','CH','CT','DDG','EG','MA','MBM','MOL','OCG','OOS','PK','PM','PT','RI','RT','SB','SH','SMP','SU','SUR','SUW','VL','WMP','WT','WYP')
*
'BF'.('BD','ET')
*
'FUEL'.('DIE','GAS')
*
'MT'.('BV','PK','PT','SH')
*
'CG'.('MA','OCG')
*
'OLOM'.('OL','OM')
*
'PAGG'.('BD','BP','BT','CA','CEB','CGF','CH','CT','DDG','ET','FT','HFCS','MA','MBM','MOL','OCG','OOS','PM','PS','PT','RI','RT','SB','SH','SMP','SUR','SUW','VL','WMP','WT','WYP','SU','BV','PK','FH','ME','MK','AGO','FST','OLN','AGR','CG','FM','FL','MTT','MT','MTW','SCA','SBE','FDP','EG','PL','FHA','FHC','DY','CE','CRP')
*
'BDSH'.('PL','SL','RL','SFL','JA','OVL','WLF','ECR','ARES','FRES','MSW','OTHW')
*
'ETSH'.('SBE','SCA','WT','MA','OCG','MOL','RT','RI','ECR','ARES','FRES','MSW','OTHW')
*
'FOODP'.('WT','MA','OCG','RI','SB','OOS','VL','SU','HFCS','FDP','BT','CH','SMP','WMP','CA','BV','PK','PT','SH','RT','FH','FL','WYP','EG','PS')
*
'DY'.('BT','CH','SMP','WMP','FDP','WYP','CA')
*
'CE'.('MA','WT','OCG','RI')
*
/;
SET MMM    'Measure parent set' /
'AA'	''
'AC..ASR'	'Acre program actual state revenue; USD/ha;'
'AC..BFR'	'Benchmark farm revenue; USD/ha;'
'AC..BM'	''
'AC..CI'	''
'AC..CO..PR'	''
'AC..CO..PT'	''
'AC..CO..SD'	''
'AC..FM..PR'	''
'AC..FM..PT'	''
'AC..FM..SD'	''
'AC..M'	''
'AC..P'	''
'AC..PG'	'Acre program guarantee; USD/ha;'
'AC..PMT'	''
'AC..PYT'	'Acre program payment; USD/ha'
'AC..R'	''
'AC..SBR'	'State based revenue; USD/ha'
'AC..SD'	''
'AC..SPR'	'Acre program coefficient; USD/ha'
'AC..TOT'	'Acre program payment; USD/t'
'AC..YLD'	'5 year Olympic average farm crop yield per ha; t/ha'
'AD..SHR'	''
'ADJ'	'Adjustment factor; %'
'ADV'	''
'ADV..ADJ'	''
'ADV..REC'	''
'AG'	''
'AGO..SHR'	''
'AH'	'Area harvested; kha'
'AH..AC'	'Area harvested under acre program; kha'
'AH..ADJ'	'Area harvested adjustment factor; kha'
'AH..AGR'	'Agricultural area required for biofuel production from biomass; kha'
'AH..EQ'	''
'AH..NTH'	'Area harvested in centre-oeste and Sudeste; kha'
'AH..PLC'	''
'AH..SHR'	'Share of product area in agricultural product area; %'
'AH..STH'	'Area harvested in the North; kha'
'AH2'	'Second and later harvested area'
'AHT'	'Total area harvested; kha'
'AO'	''
'AP'	'Farmers sale price, three year average; JPY/kg'
'APM'	'Milk assumed processing margin and other adjustment; National currency/t'
'ATLXP'	''
'AU'	'Alternative use; kt'
'BD'	'Biodiesel supported by EISA RFS; mn liters'
'BD..ADJ'	''
'BD..REC'	''
'BD..ROV'	'Biodiesel rollover to next marketing year'
'BD..ROV..MAX'	'Maximum rollover for biodiesel'
'BD..ROV..RATIO'	'Ratio driving biodiesel rollover'
'BF'	'Biofuel feedstock;'
'BF..BD..CONV'	'Conversion of the commodity in biodiesel (to be linked to the commodity)'
'BF..BD..SHR'	''
'BF..ET'	'Use of crop residues for Ethanol;'
'BF..ET..CONV'	'Conversion of the commodity in ethanol (to be linked to the commodity); t/hl'
'BF..ET..SHR'	''
'BF..SHR'	'Share of biofuel use in total consumption; %'
'BME'	'Cellulose-ethanol supported by EISA RFS; mn litres'
'BME..ADJ'	'Adjusted biomass (after waiving)'
'BME..BDSH'	'Biodiesel share'
'BME..ETS'	''
'BME..REC'	''
'BSE'	''
'CAL'	'Calories;'
'CAL..OTH'	'Calories from other foods;'
'CC'	'Biomass conversion costs; %'
'CC..LOGA'	''
'CC..LOGB'	''
'CCP'	'Countercyclical payments ; USD/t'
'CCP..PYD'	'Counter cyclical payment based yield; t/ha'
'CCP..TOT'	'Total Counter-Cyclical Payment; mio USD'
'CE..LOGA'	''
'CE..LOGB'	''
'CG..ADJ'	''
'CG..ROV'	'Corn ethanol rollover to next marketing year'
'CG..ROV..MAX'	'Maximum rollover for corn base ethanol'
'CG..ROV..RATIO'	'Ratio driving corn based ethanol rollover'
'CI'	'Cow inventory; hd'
'CI..NQT'	'Non quota cow inventories; hd'
'CI1'	''
'CI2'	''
'CON'	''
'CONV..MBM'	'Meat and bone meal production adjustment'
'COST'	'Cost of production; JPY/kg'
'CP'	'Consumer price; National currency/t'
'CP..GAS'	'Price of additive relative to gasoline; %'
'CP..SPR'	'Price spread in which substitution for additives occurs; %'
'CPCI'	'Cost of production index; index'
'CPCI..MA'	''
'CPCI..MA..SH'	''
'CPCI..MA..SHCO'	''
'CPCI..MA..SHEN'	''
'CPCI..MOL'	''
'CPCI..MOL..SH'	''
'CPCI..MOL..SHCO'	''
'CPCI..MOL..SHEN'	''
'CPCI..OCG'	''
'CPCI..OCG..SH'	''
'CPCI..OCG..SHCO'	''
'CPCI..OCG..SHEN'	''
'CPCI..RI'	''
'CPCI..RI..SH'	''
'CPCI..RI..SHCO'	''
'CPCI..RI..SHEN'	''
'CPCI..RT'	''
'CPCI..RT..SH'	''
'CPCI..RT..SHCO'	''
'CPCI..RT..SHEN'	''
'CPCI..SBE'	''
'CPCI..SBE..SH'	''
'CPCI..SBE..SHCO'	''
'CPCI..SBE..SHEN'	''
'CPCI..SCA'	''
'CPCI..SCA..SH'	''
'CPCI..SCA..SHCO'	''
'CPCI..SCA..SHEN'	''
'CPCI..SHEN'	'Energy share in the cost index; decimal'
'CPCI..SHFT'	'Fertiliser share in the cost index; decimal'
'CPCI..SHNT'	'Non-tradables share in the cost index; decimal'
'CPCI..SHSD'	'Seed share in the cost index; decimal'
'CPCI..SHTR'	'Other tradables share in the cost index; decimal'
'CPCI..VL'	''
'CPCI..VL..SH'	''
'CPCI..VL..SHCO'	''
'CPCI..VL..SHEN'	''
'CPCI..WT'	''
'CPCI..WT..SH'	''
'CPCI..WT..SHCO'	''
'CPCI..WT..SHEN'	''
'CPI'	'Consumer price index; 2000=1'
'CPN'	''
'CR'	'Crushed; kt'
'CR..COST'	''
'CR..SH'	''
'CRMAR'	'Crush margin; National currency/t'
'CRPI'	'Crop production index'
'CS'	'Consumption subsidy'
'CS..ASTN'	'Marketing support payments under ASERCA per ton; MXN/t'
'CS..TN'	'Consumption subsidy per ton; MXN/t'
'CVD'	'USA contervail duty on Canadian exports of hogs ; CAD/t'
'CW'	'Average carcass weight; t'
'CY'	'Carcass yield (carcass / live weight)'
'DEL'	'Deliveries to dairies; kt'
'DEL..QT'	'Deliveries to dairies under quota; kt'
'DIE..EFF'	'Energy content of a liter of gasoline compared to a liter of diesel; decimal'
'DIFF'	''
'DP..CE'	''
'DP..CG'	'Direct support for Ethanol production using CG; National currency/hl (/t for EU)'
'DP..FIX'	'Direct payment by area; JPY/ha'
'DP..KG'	'Total deficiency payment; JPY/kg'
'DP..MA'	''
'DP..ME'	'Marginal impact; decimal'
'DP..MOL'	''
'DP..OCG'	''
'DP..QP'	'Manufactured deficiency payment ceiling quantity; kt'
'DP..RES'	'Direct support for production using crop residues'
'DP..RI'	''
'DP..RT'	''
'DP..SBE'	'Direct support for production using SBE; USD/hl'
'DP..SCA'	''
'DP..TN'	'Direct payment to Japanese sugar producers; JPY/kg'
'DP..VAR'	'Rice direct payment, variable; JPY/t'
'DP..VL'	'Direct support for Biodiesel production using VL; national currency/kl'
'DP..WT'	'Direct support for Biodiesel production using wheat; national currency/kl'
'DPA..HA'	'Aea direct payments (PFC+MLP); USD/ha'
'DPDP..SUB'	''
'DPF'	'Fixed payments; mio USD'
'DPF..KG'	'Fixed component of the new payment to producers from 2001; JPY/kg'
'DPF..PYD'	'Fixed direct payment yield; t/ha'
'DPF..TN'	'Fixed direct payment yield; t/ha'
'DPF..TOT'	'Total Fixed Direct Payment; mio USD'
'EPA'	'Effective support payments ; national currency/ha'
'EPA..BUDGET'	''
'EPA..DP'	'Payment equivalent affecting area; EUR/ha or Eur/t'
'EPA..SHR'	''
'EPD'	'SMP subsidy; EUR/t'
'EPI'	'Effective support payments; National currency/head'
'EPI..BUDGET'	'Equivalent payment of all payments to beef and veal producers as stated in the EU budget ; EUR'
'EPI..SHR'	''
'EPP'	'Effective producer price ; JPY/kg'
'EPQ'	'Effective support payments; local currency/t'
'EPY'	'Effective support payments; local currency/t'
'ERAT'	''
'ESP'	'Effective support price; EUR/t'
'EX'	'Exports; kt'
'EX..ACP'	'Sugar ACP share of exports; %'
'EX..AID'	'Food-aid exports, year beginning 1 July; kt'
'EX..ARES'	''
'EX..ECR'	''
'EX..FRES'	''
'EX..JA'	''
'EX..MA'	''
'EX..MOL'	''
'EX..MSW'	''
'EX..OCG'	''
'EX..OTH'	''
'EX..OTHW'	''
'EX..OVL'	''
'EX..PL'	''
'EX..PP'	''
'EX..PRO'	'Exports of products containing sugar; kt'
'EX..PRO..CAN'	'Exports of products containing sugar; kt'
'EX..QPEX'	''
'EX..RI'	''
'EX..RL'	''
'EX..RT'	''
'EX..SBE'	''
'EX..SCA'	''
'EX..SFL'	''
'EX..SH'	''
'EX..SHR'	'Share of ODP exports subsidies going to WMP; %'
'EX..SL'	''
'EX..SUB'	'Subsidised exports; kt'
'EX..SUB..LIM..VAL'	'Value of WTO limit on exports; mio CAD'
'EX..SUBLB'	'Parameter; decimal'
'EX..SUBLIM'	''
'EX..SUBSHR'	''
'EX..SUBUB'	'Parameter; decimal'
'EX..TOT'	''
'EX..TRND'	''
'EX..UNS'	'Unsubsidised exports; kt'
'EX..WLF'	''
'EX..WT'	''
'EX..WTOFY'	'Subsidised export limit, financial year; kt cw'
'EX..XUSA'	'Exports to USA'
'EXL'	'Live exports; kt'
'EXL..PP'	''
'EXL..QPEX'	''
'EXL..SHR'	''
'EXL..XUSA'	''
'EXM'	'Meat exports; kt'
'EXM..ATL'	''
'EXM..PAC'	''
'EXM..PP'	''
'EXM..QPEX'	''
'EXM..SUB'	'Meat subsidized exports; kt;'
'EXM..SUBLIM'	''
'EXM..UNS'	'Meat unsubsidized exports; kt;'
'EXM..XCHN'	''
'EXP'	'Exports price; local currency/t'
'EXP..ADJ'	''
'FAD'	'Feed adjuster ; USD/cwt'
'FAT'	'Fat; %'
'FC..CG'	''
'FC..SBE'	''
'FC..VL'	''
'FC..WT'	''
'FCR'	'Feed conversion ratio'
'FCR..ADJ'	'Adjustment to the feed conversion ratio'
'FCR..FE'	'Feed conversion ratio of specialized or commercial farms'
'FE'	'Feed consumption; kt'
'FE..EST'	''
'FE..FHA'	''
'FE..SH'	''
'FE..SHR'	'Feed share in coarse grains feed; decimal'
'FE..TEST'	''
'FECI'	'Feed expenditure index; %'
'FECI..2010'	''
'FECI1'	''
'FECI2'	''
'FECI3'	''
'FL'	''
'FL..ARES'	''
'FL..ARESSH'	''
'FL..ECR'	''
'FL..ECRSH'	''
'FL..FRES'	''
'FL..FRESSH'	''
'FL..MA'	''
'FL..MASH'	''
'FL..MOL'	''
'FL..MOLSH'	''
'FL..MSW'	''
'FL..MSWSH'	''
'FL..OCG'	''
'FL..OCGSH'	''
'FL..OTHW'	''
'FL..OTHWSH'	''
'FL..RI'	''
'FL..RISH'	''
'FL..RT'	''
'FL..RTSH'	''
'FL..SBE'	''
'FL..SBESH'	''
'FL..SCA'	''
'FL..SCASH'	''
'FL..WT'	''
'FL..WTSH'	''
'FM..DF'	'Fluid milk price differential;'
'FO'	'Food consumption; kt'
'FO..ADJ'	'Adjustment factor'
'FO..BT'	''
'FO..BV'	''
'FO..CH'	''
'FO..EG'	''
'FO..FDP'	''
'FO..FH'	''
'FO..HFCS'	''
'FO..IM'	'Oilseed food consumption from imports; kt'
'FO..MA'	''
'FO..NF'	''
'FO..OCG'	''
'FO..PK'	''
'FO..PT'	''
'FO..RI'	''
'FO..RT'	''
'FO..SH'	''
'FO..SHR'	'Food share; decimal'
'FO..SMP'	''
'FO..SU'	''
'FO..VL'	''
'FO..WMP'	''
'FO..WT'	''
'FOCI'	'Food expenditure index; index'
'FOE'	'Food expenditures;'
'FPI'	''
'FPIW'	''
'FU'	'Farm use; kt'
'GAS..BME'	''
'GDP..2010'	''
'GDPC..US'	''
'GDPC..US..2010'	''
'GDPD'	'Gross domestic product deflator; 2000=1'
'GDPD..2000'	''
'GDPD..2006'	''
'GDPD..2005'	'Gross domestic product deflator 2005; 2000=1'
'GDPD..2007'	'Gross domestic product deflator 2007; 2000=1'
'GDPD..2008'	'Gross domestic product deflator 2008; 2000=1'
'GDPD..2010'	''
'GDPI'	'Gross domestic product index; 2000=1'
'GDPUS..PC'	''
'GHG'	''
'GHG..REF'	''
'GHGLUC'	''
'GHGLUC..ARES'	''
'GHGLUC..ECR'	''
'GHGLUC..FRES'	''
'GHGLUC..JA'	''
'GHGLUC..MA'	''
'GHGLUC..MOL'	''
'GHGLUC..MSW'	''
'GHGLUC..OCG'	''
'GHGLUC..OTHW'	''
'GHGLUC..OVL'	''
'GHGLUC..PL'	''
'GHGLUC..RI'	''
'GHGLUC..RL'	''
'GHGLUC..RT'	''
'GHGLUC..SAV'	''
'GHGLUC..SBE'	''
'GHGLUC..SCA'	''
'GHGLUC..SFL'	''
'GHGLUC..SL'	''
'GHGLUC..WLF'	''
'GHGLUC..WT'	''
'GHGTOT'	''
'GHGTOT..ARES'	''
'GHGTOT..ECR'	''
'GHGTOT..FRES'	''
'GHGTOT..JA'	''
'GHGTOT..MA'	''
'GHGTOT..MOL'	''
'GHGTOT..MSW'	''
'GHGTOT..OCG'	''
'GHGTOT..OTHW'	''
'GHGTOT..OVL'	''
'GHGTOT..PL'	''
'GHGTOT..RI'	''
'GHGTOT..RL'	''
'GHGTOT..RT'	''
'GHGTOT..SAV'	''
'GHGTOT..SBE'	''
'GHGTOT..SCA'	''
'GHGTOT..SFL'	''
'GHGTOT..SL'	''
'GHGTOT..WLF'	''
'GHGTOT..WT'	''
'GHGWTW'	''
'GHGWTW..ARES'	''
'GHGWTW..ECR'	''
'GHGWTW..FRES'	''
'GHGWTW..JA'	''
'GHGWTW..MA'	''
'GHGWTW..MOL'	''
'GHGWTW..MSW'	''
'GHGWTW..OCG'	''
'GHGWTW..OTHW'	''
'GHGWTW..OVL'	''
'GHGWTW..PL'	''
'GHGWTW..RI'	''
'GHGWTW..RL'	''
'GHGWTW..RT'	''
'GHGWTW..SAV'	''
'GHGWTW..SBE'	''
'GHGWTW..SCA'	''
'GHGWTW..SFL'	''
'GHGWTW..SL'	''
'GHGWTW..WLF'	''
'GHGWTW..WT'	''
'HFCS'	'Used for HFCS; kt'
'HR'	''
'IM'	'Imports; kt'
'IM..ACP'	'Sugar ACP share of imports; %'
'IM..ADJ'	'Imports, non quota; 1t in raw sugar equivalent'
'IM..ARES'	''
'IM..ARESSH'	''
'IM..EBA'	'Imports, EBA; kt'
'IM..ECR'	''
'IM..ECRSH'	''
'IM..EXO'	''
'IM..FRES'	''
'IM..FRESSH'	''
'IM..JA'	''
'IM..LIMIT'	''
'IM..LIMIT..MEX'	''
'IM..MA'	''
'IM..MAR'	'Receipts from the mark-up on soybean imports for food use per ton; KRW/t'
'IM..MASH'	''
'IM..MOL'	''
'IM..MOLSH'	''
'IM..MSW'	''
'IM..MSWSH'	''
'IM..OADV'	'Imports for other advanced mandate'
'IM..OCG'	''
'IM..OCGSH'	''
'IM..OQ'	'Over Quota Imports ; MT () (dw)'
'IM..OTH'	'Imports, excluding intra trade, other; kt rse'
'IM..OTHW'	''
'IM..OTHWSH'	''
'IM..OVL'	''
'IM..PL'	''
'IM..PP'	''
'IM..PRO'	'Of products containing sugar; 1t in raw sugar equivalent'
'IM..PRO..CAN'	'From Canada,of products containing sugar; 1t in raw sugar equivalent'
'IM..QCIM'	''
'IM..REX'	'Other quota imports; kt'
'IM..RI'	''
'IM..RISH'	''
'IM..RL'	''
'IM..RT'	''
'IM..RTSH'	''
'IM..SBE'	''
'IM..SBESH'	''
'IM..SCA'	''
'IM..SCASH'	''
'IM..SFL'	''
'IM..SHR'	''
'IM..SHRATL'	''
'IM..SHREUN'	''
'IM..SHREUN..EUN'	''
'IM..SHRPAC'	''
'IM..SL'	''
'IM..ST'	''
'IM..SUP'	''
'IM..TMAR'	'Receipts from the mark-up on soybean imports for food use; Mil. KRW'
'IM..TOT'	''
'IM..TRND'	''
'IM..TRQ'	''
'IM..WLF'	''
'IM..WT'	''
'IM..WTSH'	''
'IM..XMEX'	''
'IML'	'Live imports; kt'
'IML..PP'	''
'IML..QCIM'	''
'IMM'	'Meat imports; kt'
'IMM..FIX'	''
'IMM..PP'	''
'IMM..QCIM'	''
'IMP'	'Import price;'
'IMP..ADJ'	'Quality adjustment factor'
'IMP..ITQ'	''
'IMP..OTQ'	''
'IMP..XMEX'	''
'INS..LCR'	''
'INS..LCR..SCO'	''
'INS..LCR..STAX'	''
'INS..PCT'	''
'INS..PP..E'	''
'INS..RT'	''
'INS..SCO..PT'	''
'INS..SCO..RT'	''
'INS..STAX..LIAB'	''
'INS..STAX..PT'	''
'INS..STAX..RT'	''
'INS..SUB'	''
'INS..YLD'	''
'INV'	'Production capacity investment'
'IP'	''
'IST'	'Ending intervention stocks; kt'
'LEVY'	'Levy; cents per dozen or EUR/t'
'LI'	'Live inventory; head'
'LI..OTH'	'Catlle and calves excluding cows inventory; hd'
'LI1'	''
'LR'	'Loan rate; USD/t'
'LR..AC'	'Loan rate under the acre program; USD/t'
'LR..TN'	'Loan rate per ton; USD/t'
'LSP'	'Lower stabilisation price; JPY/t'
'LU'	'Land use'
'LU..BAS'	''
'LU..Min'	''
'LU..SHR'	'Land use share'
'LU..SHR..EQ'	'Land use share equation'
'MA..ADJ'	''
'MA..REC'	''
'MA..ROV'	''
'MAR'	'Margin between wholesale and retail; National currency/unit of product'
'MAR..ET'	''
'MAR..EXO'	'Gasoline margin; national currency/ kl'
'MBD'	'Mandated blending demand'
'MBD..ADJ'	''
'MBD..LAW'	''
'MBD..SH'	''
'MIP'	'Approximate effective minimum import price (hypothetical average) following URAA; previously equal to the Standard Import Price; JPY/t'
'MLP..AC'	'Marketing loan benefits under acre program; USD/t'
'MLP..AV'	'Marketing loan benefits average; USD/t'
'MLP..TN'	'Marketing loan benefits; USD/t'
'MLP..TOT'	'Total Marketing Loan Payments; mio USD'
'MP..SPR'	''
'MPP'	''
'MPP..PREM'	''
'MSP'	'Minimum support price;'
'MUP'	'Mark-up; %'
'NC..BME'	'Net production costs for ETHANOL from Biomass; USD/hl'
'NC..CE'	''
'NC..CG'	'Net cost from coarse grains; national currency/hl'
'NC..CG..CC'	'Fix capital cost (moving with time); national currency/hl'
'NC..CG..OC'	'Fix other exogenous cost (moving with time); national currency/hl'
'NC..CG..OIL'	'Slope parameter of cost of bio-fuel vs fossil fuel; barrel oil/ kl of ET'
'NC..CG..OILC'	'Constant (moving with time); per hl of ET'
'NC..RES'	'Net production costs for ETHANOL from agricultural residues'
'NC..SBE'	'Net production cost of ETHANOL using SBE; National currency/kl;'
'NC..SBE..CC'	'Fix capital cost (moving with time); National currency/kl;'
'NC..SBE..OC'	'Fix other exogenous cost (moving with time)National currency/kl'
'NC..SBE..OIL'	'Slope parameter of cost of bio-fuel vs fossil fuel; barrel oil/ kl of ET'
'NC..SBE..OILC'	'Constant (moving with time); per kl of ET'
'NC..VL'	'Net production cost of BIODIESEL using VL; National currency/kl;'
'NC..VL..CC'	'Fix capital cost (moving with time); National currency per hl'
'NC..VL..OC'	'Fix other exogenous cost (moving with time); national currency/hl'
'NC..VL..OIL'	'Sope parameter of cost of bio-fuel vs fossil fuel; barrel / hl'
'NC..VL..OILC'	'Constant (moving with time); National currency/hl;'
'NC..WT'	'Net production cost of ETHANOL using WT; National currency/kl;'
'NC..WT..CC'	'Fix capital cost (moving with time); National currency/kl'
'NC..WT..OC'	'Fix other exogenous cost (moving with time); National currency/kl'
'NC..WT..OIL'	'Slope parameter of cost of bio-fuel vs fossil fuel; barrel oil/ hl of ET'
'NC..WT..OILC'	'Constant (moving with time); per hl of ET'
'NFS'	'Non-fat solid content; decimal'
'NQT'	''
'NQT..EXSHR'	''
'NT'	'Net trade; kt'
'NT..ATL'	'Net trade atlantic; kt'
'NT..FMD'	'Net trade foot and mouth disease affected region; kt'
'NT..PAC'	'Net trade pacific; kt'
'NTL'	''
'OADV..ADJ'	''
'OADV..REC'	''
'OAQ..SBE'	'Overall allotment quantity of sugar from beet; kt'
'OAQ..SCA'	'Overall allotment quantity of sugar fromcane; kt'
'OTH'	''
'OU'	'Other use; kt'
'PACXP'	''
'PAH'	'Fixed direct payment area; Kha'
'PAH..PCT'	'Fixed direct payment area percentage change; %'
'PARM'	''
'PC'	'Per-capita consumption; kg/capita'
'PCST'	''
'PLC..PMT'	''
'PLC..PR'	''
'PLC..PYD'	''
'PM'	'Processing margin'
'PMA'	'Price margin between sugar/ethanol and sugar cane'
'POP'	'Population; thousand'
'POP..2010'	''
'PP'	'Producer price; national currency/t'
'PP..2004'	'Producer price base year 2004; index'
'PP..2006'	'Producer price base year 2006; index'
'PP..2007'	'Producer price base year 2007; index'
'PP..2008'	''
'PP..AC'	''
'PP..AN'	''
'PP..BAL'	''
'PP..BAL..FAT'	''
'PP..BAL..NFS'	''
'PP..BD'	''
'PP..BD..RATIO'	'Price ratio to biodiesel'
'PP..BD..TRDRATIO'	'Trend of price ratio to biodiesel'
'PP..BME'	'Production using Biomass; million litres'
'PP..BR'	'Producer price used in Brazil'
'PP..CWB'	'Canadian Wheat Board producer final realized price, Bread wheat Thunder Bay; CAD/t'
'PP..ET'	''
'PP..ET..RATIO'	'Rice ratio to ethanol'
'PP..ET..TRDRATIO'	'Trend of price ratio to ethanol'
'PP..EX'	''
'PP..EXO'	''
'PP..FAT'	'Market clearing price for milk fat; national currency/t'
'PP..FE'	'Price for feed'
'PP..FEEXO'	''
'PP..FM'	'Milk price, class 1 fluid milk price, Canada; CAD/t'
'PP..FOD'	''
'PP..IM'	'Milk price, industrial milk target return (annual average calculation); CAD/t'
'PP..IM..SM'	''
'PP..NFS'	'Milk Market clearing price for milk non-fat ; national currency/t'
'PP..NQT'	''
'PP..NTH'	'Soybean return per hectares in centre-oeste and Sudeste; BRL/ha'
'PP..PR'	''
'PP..PRAT'	'Quality adjustment factor; decimal'
'PP..QT'	''
'PP..SM'	''
'PP..STH'	'Soybean return per hectares in centre-oeste and Sudeste; BRL/ha'
'PP..TB'	''
'PP..VAN'	''
'PP..WHO'	''
'PP1'	''
'PP2'	''
'PP3'	''
'PR'	''
'PR..DIE'	'Price ratio between Biodiesel and diesel, market prices; ratio'
'PR..GAS'	'Price ratio between ethanol and gasoline, market prices; ratio'
'PREM..DIE'	''
'PREM..FFV'	'Ethanol premium above energy equivalent price, share of gasoline price; decimal'
'PREM..GAS'	'Maximum premium price of ethanol in low-level blends, relative to gasoline price, ratio'
'PRST'	'Private ending stocks; kt'
'PXE..BASE'	''
'PXI..BASE'	''
'QC'	'Total consumption; kt'
'QC..ACP'	'ACP share of total consumption; decimal'
'QC..ADD'	''
'QC..ARES'	''
'QC..BF'	''
'QC..BLD'	''
'QC..ECR'	''
'QC..FM'	'Fluid milk consumption; kt'
'QC..FRES'	''
'QC..FUEL'	'Fuel milk consumption; kt'
'QC..FUEL..YEAR'	''
'QC..HBLD'	''
'QC..JA'	''
'QC..LBLD'	''
'QC..MA'	''
'QC..MAN'	''
'QC..MOL'	''
'QC..MSW'	''
'QC..OBL'	''
'QC..OCG'	''
'QC..OTHW'	''
'QC..OVL'	''
'QC..PL'	''
'QC..RI'	''
'QC..RL'	''
'QC..RT'	''
'QC..SBE'	''
'QC..SCA'	''
'QC..SFL'	''
'QC..SL'	''
'QC..TOT'	''
'QC..TRANS'	''
'QC..TRANS..SHR'	''
'QC..WLF'	''
'QC..WT'	''
'QC..YEAR'	''
'QCS'	'Consumption share; decimal'
'QCS..ADD'	'Share in gasoline as an additive, energy equivalent; calculation'
'QCS..ADDM'	'Additive share in gasoline, mandatory; decimal'
'QCS..CALC'	''
'QCS..ECR..OBL'	''
'QCS..EFF'	''
'QCS..ETV'	''
'QCS..FFV'	'Used as neat fuel by flexi-fuel vehicles, share, energy equivalent; calculation'
'QCS..FFV..EXO'	''
'QCS..HBLD'	'Share in high-level blends used in FFV s, energy equivalent; ratio'
'QCS..LBLD'	'Share in gasoline in a low level blend, energy equivalent; ratio'
'QCS..LBLD..EQ'	'Share in gasoline in a low level blend, energy equivalent for mandate countries; decimal'
'QCS..LIMIT'	'Upper limit for ethanol in low-level blends, share'
'QCS..LIMIT..VOL'	''
'QCS..MA..OBL'	''
'QCS..MAN'	''
'QCS..OADV..OBL'	''
'QCS..OBL'	'Blending obligation, share, volume basis'
'QCS..OBL..VOL'	''
'QCS..RES'	''
'QCS..ROV'	''
'QCS..SEC'	''
'QCS..WST'	''
'QCSV'	''
'QD'	'Government domestic use plus statistical differences; kt'
'QP'	'Production; kt'
'QP..2012'	''
'QP..ACP'	'Sugar ACP share of production; ratio'
'QP..ARES'	''
'QP..BAS'	''
'QP..BASE'	''
'QP..BME'	'Production using Biomass; million litres'
'QP..BV'	'Production from cattle'
'QP..CG'	'Total domestic production of coarse grains; kt'
'QP..CG..CONV'	'Energy conversion from coarse grains; decimal'
'QP..CG..VAL'	'Value of by-products from coarse grains'
'QP..CGSHR'	''
'QP..COW'	''
'QP..DS'	'Direct sales; kt'
'QP..DY'	'Production from pure cow s milk; kt'
'QP..ECR'	''
'QP..ENDO'	''
'QP..FD'	'Sum of specialized and commercial farms'
'QP..FRES'	''
'QP..IM'	'For processing; kt;'
'QP..JA'	'Total domestic production of jatropha; kt'
'QP..MA'	''
'QP..MA..CONV'	''
'QP..MA..VAL'	''
'QP..MOL'	'Total domestic production of molasses; kt'
'QP..MOL..VAL'	''
'QP..MSW'	''
'QP..NAGR'	'Biodiesel Production from non-commodity feedstocks'
'QP..NAGRD'	''
'QP..NAGRE'	''
'QP..ND'	'Production other that from cow s milk; kt'
'QP..NQT'	'Production underlined supply; kt;'
'QP..OCG'	''
'QP..OCG..CONV'	''
'QP..OCG..VAL'	''
'QP..OTH'	''
'QP..OTHW'	''
'QP..OVL'	''
'QP..PK'	'Production from swine'
'QP..PL'	''
'QP..PT'	'Production from poultry including feather meal'
'QP..RES'	'Production from Agricultural residues; million litres'
'QP..RESSHR'	''
'QP..RI'	''
'QP..RI..VAL'	''
'QP..RL'	''
'QP..RT'	'Total domestic production of root tubers; kt'
'QP..RT..CONV'	'Energy conversion from root tubers; decimal'
'QP..RT..VAL'	''
'QP..SBE'	'Production from sugar beet; kt'
'QP..SBE..CONV'	''
'QP..SBE..VAL'	'Revenues for other by-products; National currency/kl;'
'QP..SCA'	'Total domestic production of sugar cane; kt'
'QP..SCA..CONV'	'Conversion factor between Energy-rich feed quantity produce by ethanol quantity produce; decimal'
'QP..SCA..VAL'	''
'QP..SEC'	''
'QP..SFL'	''
'QP..SH'	'Production from swine'
'QP..SL'	''
'QP..SU'	'Ethanol from surplus sugar; kl'
'QP..T'	'HFCS production test variable; kt'
'QP..TOT'	''
'QP..VL'	'Total domestic production of vegetable oil; KT'
'QP..VL..VAL'	'Value of by-products from vegetable oil; kt'
'QP..WLF'	''
'QP..WT'	'Total domestic production of wheat; kt'
'QP..WT..CONV'	'Energy conversion from wheat; decimal'
'QP..WT..VAL'	'Value of by-products from wheat;'
'QPC..CE'	''
'QPC..CG'	'Ethanol Production capacities using CG, weighted for the year; million litres'
'QPC..SBE'	'Ethanol Production capacities using SBE; million litres'
'QPC..VL'	'Total domestic production capacity from vegetable oil; mn litres'
'QPC..WT'	'Total domestic production capacity from wheat; mn litres'
'QPR..CE'	''
'QPR..CG'	'Capacity Use Rate; decimal'
'QPR..SBE'	'Capacity Use Rate; decimal'
'QPR..VL'	'Capacity Use Rate; decimal'
'QPR..WT'	'Capacity Use Rate; decimal'
'QPRL..CE'	''
'QPRL..CG'	'Lower bound for the use rate; decimal'
'QPRL..SBE'	'Lower bound for the use rate; decimal'
'QPRL..VL'	'Lower bound for the use rate; decimal'
'QPRL..WT'	'Lower bound for the use rate; decimal'
'QPRU..CE'	''
'QPRU..CG'	'Upper bound for the use rate; decimal;'
'QPRU..SBE'	'Upper bound for the use rate; decimal;'
'QPRU..VL'	'Upper bound for the use rate; decimal;'
'QPRU..WT'	'Upper bound for the use rate; decimal;'
'QPS'	'Slaughtered production; kt'
'QT'	'Quotas; kt'
'QT..CHG'	''
'QT..XUSA'	'Export quota to USA; kt'
'RES'	'Seasonnal adjustment on prices; JPY/kt;'
'RET'	'Average returns;'
'RET1'	''
'RET2'	''
'REV'	'Revenue from imports and HFCS ; JPY/kg'
'RH'	'Returns per hectare; national currency/ha'
'RH..E'	'Expected market return per hectare east; national currency/ha'
'RH..NQT'	''
'RH..NTH'	'Return per hectares in centre-oeste and Sudeste; national currency/ha'
'RH..STH'	'Return per hectares in South; national currency/ha'
'RH..W'	'Expected market return per hectare west; national currency/ha'
'RH1'	''
'RH2'	''
'RH3'	''
'RH4'	''
'RM..MA'	''
'RM..MA..LAG1'	''
'RM..MA..LAG2'	''
'RM..MA..LAG3'	''
'RM..MOL'	''
'RM..MOL..LAG1'	''
'RM..MOL..LAG2'	''
'RM..MOL..LAG3'	''
'RM..OCG'	''
'RM..OCG..LAG1'	''
'RM..OCG..LAG2'	''
'RM..OCG..LAG3'	''
'RM..RI'	''
'RM..RI..LAG1'	''
'RM..RI..LAG2'	''
'RM..RI..LAG3'	''
'RM..RT'	''
'RM..RT..LAG1'	''
'RM..RT..LAG2'	''
'RM..RT..LAG3'	''
'RM..SBE'	''
'RM..SBE..LAG1'	''
'RM..SBE..LAG2'	''
'RM..SBE..LAG3'	''
'RM..SCA'	''
'RM..SCA..LAG1'	''
'RM..SCA..LAG2'	''
'RM..SCA..LAG3'	''
'RM..VL'	''
'RM..VL..LAG1'	''
'RM..VL..LAG2'	''
'RM..VL..LAG3'	''
'RM..WT'	''
'RM..WT..LAG1'	''
'RM..WT..LAG2'	''
'RM..WT..LAG3'	''
'ROR..CG'	'Rate of return from coarse grains; national currency/hl'
'ROR..SBE'	'Rate of return from sugar beet; national currency/hl'
'ROR..VL'	'Rate of return from vegetable oil; national currency/hl'
'ROR..WT'	'Rate of return from wheat; national currency/hl'
'RP'	'Reference price; national currencyt'
'RSP'	'Resale price; JPY/kg'
'RV'	'Revenue from imports and HFCS ; JPY/kg'
'RV..ET'	'Residue value per tonne of biomass in the production of Ethanol; national currency/t'
'SBE..LOGA'	'Parameter in Logistic function; decimal; EU'
'SBE..LOGB'	'Parameter in Logistic function; decimal; EU'
'SCASBE'	''
'SD'	'Statistical difference'
'SD..ARES'	''
'SD..ECR'	''
'SD..FRES'	''
'SD..JA'	''
'SD..MA'	''
'SD..MOL'	''
'SD..MSW'	''
'SD..OCG'	''
'SD..OTHW'	''
'SD..OVL'	''
'SD..PL'	''
'SD..RI'	''
'SD..RL'	''
'SD..RT'	''
'SD..SBE'	''
'SD..SCA'	''
'SD..SFL'	''
'SD..SL'	''
'SD..WLF'	''
'SD..WT'	''
'SFP'	'Single farm payment factor ; decimal'
'SFP..CF'	''
'SGP'	'Maximum special safeguard price following URAA, converted to carcass weight using official .75; JPY/t, cw'
'SH..CG'	'Share produced from coarse grains; ratio'
'SH..JA'	'Share produced from jatropha; ratio'
'SH..MA'	''
'SH..MOL'	'Share produced from molasses; ratio'
'SH..NAGR'	'Share produced from non-commodity feedstock; ratio'
'SH..NAGRD'	''
'SH..NAGRE'	''
'SH..OCG'	''
'SH..RT'	'Share produced from root tubers; ratio'
'SH..SCA'	'Share produced from sugar cane; ratio'
'SH..VL'	'Share produced from vegetable oil; ratio'
'SH..WT'	'Share produced from wheat; ratio'
'SHP'	''
'SHR'	''
'SHR..CG'	''
'SHR..JA'	''
'SHR..MOL'	''
'SHR..NAGR'	''
'SHR..NAGRD'	''
'SHR..NAGRE'	''
'SHR..RT'	''
'SHR..SCA'	''
'SHR..VL'	'Share of vegetable oil in biodiesel production; %'
'SHR..WT'	''
'SIP'	'Standard import price; JPY/t, cw'
'SLH'	''
'SMP'	''
'SP'	''
'SPE'	'Butter effective support price; EUR/t'
'SPV'	'Support price; EUR/t'
'SSQ'	''
'ST'	'Ending stocks; kt'
'ST..ACP'	'ACP share of stocks; ratio'
'ST..CF'	''
'ST..MIN'	''
'ST..QC'	''
'ST1'	'Transaction stocks; kt'
'ST2'	'Intervention stocks trigger; kt'
'STU'	''
'SU'	''
'SWG'	'Used for seeteners; kt'
'TARA'	''
'TARS'	''
'TAS'	'Import tariff, specific; national/kl'
'TAV'	'Tariff ad valorem'
'TAV..IQS'	'Ad valorem tariff, in quota; %'
'TAV..NQA'	''
'TAV..NQS'	'Import ad valorem tariff; %'
'TAV..OQS'	'Import ad valorem tariff (out-of-quota tariff); %'
'TAV..SSQ'	''
'TAVE'	'Export ad valorem tariff; %'
'TAVI'	'Import ad valorem tariff; %'
'TAVI..IQS'	''
'TAVI..OQS'	''
'TAX'	'Tax'
'TAX..CRD'	'Tax credit; USD/hl'
'TC'	'Transport costs; USD/t'
'TC..NTH'	'Transport cost of oilseeds from the highlands to the coast; BRL/ha'
'TCE'	'Parameter set to'
'TCI'	''
'TOT..ADJ'	'Total adjusted (including waiving)'
'TOT..EFF'	'Total effective (including rollover)'
'TOT..EFF..REC'	''
'TOT..REC'	''
'TP'	'Target price; national currency/kg;'
'TP..TN'	''
'TRC'	'Transport cost in Canada, (actual trans. cost and crow subs.); national currency/t;'
'TRC..CAN'	''
'TRG'	'CCP triger price (until 2007 37.346 Boston price, after 2007 adjusted by the feed cost FAD); USD/t'
'TRND'	''
'TRQ'	'Import tarrif quota; kt'
'TRQ..BAL'	''
'TRQ..CXL'	''
'TRQ..OTH'	''
'TRQ..SUP'	''
'TRQ..XMEX'	''
'TSP'	'Specific tariff'
'TSP..IQS'	'Import tariff in quota, scheduled; EUR/t;'
'TSP..LIM'	'Limit of import tariff scheduled; EUR/t;'
'TSP..OQS'	'Import tariff out of quota, scheduled; EUR/t'
'TVE'	'Parameter set to'
'TVI'	''
'USACY'	''
'USAGDPD'	''
'VAT'	'VAT applied ; percent'
'VL..LOGA'	'Parameter in Logistic function; decimal'
'VL..LOGB'	'Parameter in Logistic function; decimal'
'VNC..CE'	''
'VNC..CG'	'Variable net production cost of ETHANOL using CG;'
'VNC..SBE'	'Variable net production cost of ETHANOL using sugar beet;'
'VNC..VL'	'Variable net production cost of ETHANOL using vegetable oil;'
'VNC..WT'	'Variable net production cost of ETHANOL using wheat;'
'VST'	'Change in stocks; kt'
'VST..PRST'	'Change in private stocks ; kt'
'WAIVER'	'Waiving percentage'
'WAS'	'Waste (statistical difference between ; kt'
'WLDXP'	''
'WP'	''
'XP'	'World reference price; USD/t'
'XP..2000'	'World reference price 2000; USD/t'
'XP..2005'	'World reference price 2005; USD/t'
'XP..2007'	'World reference price 2007; USD/t'
'XP..2008'	'World reference price 2008; USD/t'
'XP1'	''
'XP2'	''
'XR'	'Exchange rate; National currency/USD'
'XR..2000'	'Exchange rate 2000; national currency/USD'
'XR..2005'	'Exchange rate 2005; national currency/USD'
'XR..2007'	'Exchange rate 2007; national currency/USD'
'XR..2008'	'Exchange rate 2008; national currency/USD'
'XR..2010'	''
'YLD'	'Yield; t/ha'
'YLD..AVE'	'Yield 5 years average; t/ha'
'YLD..AVE..SBE'	'To be deleted'
'YLD..AVE..SCA'	'To be deleted'
'YLD..OOS'	''
'YLD..P'	''
'YLD..RAT'	''
'YLD..SB'	''
'YLD..SBE'	'Yield from sugar beet'
'YLD..SCA'	'Yield from sugar cane'
'XR..2006'	''
'CPCI..PL'	''
'CPCI..PL..SH'	''
'CPCI..PL..SHCO'	''
'CPCI..PL..SHEN'	''
'CPCI..RL'	''
'CPCI..RL..SH'	''
'CPCI..RL..SHCO'	''
'CPCI..RL..SHEN'	''
'CPCI..SFL'	''
'CPCI..SFL..SH'	''
'CPCI..SFL..SHCO'	''
'CPCI..SFL..SHEN'	''
'CPCI..SL'	''
'CPCI..SL..SH'	''
'CPCI..SL..SHCO'	''
'CPCI..SL..SHEN'	''
'DP..PL'	''
'DP..RL'	''
'DP..SFL'	''
'DP..SL'	''
'EXL..HD'	''
'EXM..T'	''
'FL..HBLD'	''
'FL..LBLD'	''
'IML..HD'	''
'LIS'	''
'PP..LW'	''
'QC..TRANS..H'	''
'QC..TRANS..HBLD'	''
'QC..TRANS..LBLD'	''
'QCS..OBL..ADJ'	''
'QCS..OBL..VOL..ADJ'	''
'QCS..OBL..VOL..ADJSH'	''
'QP..HS'	''
'QP..OT'	''
'QP..PL..VAL'	''
'QP..RL..VAL'	''
'QP..SFL..VAL'	''
'QP..SL..VAL'	''
'RM..PL'	''
'RM..PL..LAG1'	''
'RM..PL..LAG2'	''
'RM..PL..LAG3'	''
'RM..RL'	''
'RM..RL..LAG1'	''
'RM..RL..LAG2'	''
'RM..RL..LAG3'	''
'RM..SFL'	''
'RM..SFL..LAG1'	''
'RM..SFL..LAG2'	''
'RM..SFL..LAG3'	''
'RM..SL'	''
'RM..SL..LAG1'	''
'RM..SL..LAG2'	''
'RM..SL..LAG3'	''
'QP..PL..LAG1'	''
'QP..PL..LAG2'	''
'QP..PL..LAG3'	''
'QP..MA..LAG1'	''
'QP..MA..LAG2'	''
'QP..MA..LAG3'	''
'QP..SCA..LAG1'	''
'QP..SCA..LAG2'	''
'QP..SCA..LAG3'	''
'QP..SL..LAG1'	''
'QP..SL..LAG2'	''
'QP..SL..LAG3'	''
'QP..MOL..LAG1'	''
'QP..MOL..LAG2'	''
'QP..MOL..LAG3'	''
'AH..SHR..PS'	''
'FO..PS'	''
'FO..PC'	''
'FO..PC..CALO'	''
'FO..PC..PROT'	''
'FO..PC..FAT'	''
'SHR..MA '	''
'EPA..BUDGET..MT'	''
'OQT'	''
'SP..ACT'	''
'AC..PR..PER'	''
'IM..PLSH'	''
'IM..SLSH'	''
'IM..RLSH'	''
'IM..SFLSH'	''
'IM..OVLSH'	''
'IM..WLFSH'	''
'IM..JASH'	''
'IM..TN'	''
'TAR'	''
'IM..QT'	''
'TAV..KG'	''
'QT..MT'	''
'IM..TAR..WTO'	''
'TSP..USD'	''
'BP'	''
'BR'	''
'DCA'	''
'EPI..BUDGET..MT'	''
'SP..MECU'	''
'USP'	''
'GATT'	''
'SP..LT..CENTS '	''
'SP..TN'	''
'TP..LT'	''
'QCS..MAN..PER'	''
'taV..DEN..PER'	''
'TAV..PER'	''
'TAVE..PER'	''
'TAX..CONS'	''
'TAX..DIFF'	''
'CRP'	''
'INS..STAX..PT..PER'	''
'PRT..AH'	''
'PRT..PAH'	''
'XR..UNIT1000'	''
'QCSV..lst1'	''
'QCSV..lst2'	''
'QP..WASTE'	''
'QP..WF'	''
'XP..REAL'	''
'PP..USD'	'Price in USD'
'QP..MSD'	'Production expressed in milk solid'
'FO..MSD'	'Food consumption expressed in milk solid'
'Qp..MT'	''
'Qp..SCA..mt'	''
'Qp..MA..MT'	''
'QC..MT'	''
'FL..MT'	''
'NT..mt'	''
'PP..USD..REAL'	''
'AC..PER'	''
'PP..REAL'	''
'PP..IM..CT'	''
'MP..CS'	''
'QO'	''
'QO..MT'	''
'EX..MT'	''
'EX..CALO'	''
'EX..PROT'	''
'EX..FAT'	''
'IM..CALO'	''
'IM..PROT'	''
'IM..FAT'	''
/;
*
SET mbalpos(MMM)    'Main market balance positions' 
	/'QP','QC','EX','IM','ST','NT','FO','FE','BF','SWG','CR','VST'/;
*
SET areas(MMM)    'Area related items' 
	/'LU','AH','AH2'/;
*
SET cpci_shrs(MMM)    'CPCI shares' 
	/'CPCI..SHEN','CPCI..SHFT','CPCI..SHTR','CPCI..SHNT','CPCI..SHSD'/;
*
SET PerCaps(MMM)    'per capita consumptions' 
	/'FO..PC','FO..PC..CALO','FO..PC..PROT','FO..PC..FAT'/;
*
SET aggregQ(MMM)    'items that can be aggregated by simple summation' 
	/'QP','QC','EX','IM','ST','NT','FO','FE','BF','SWG','CR','VST','AH','LU','POP','NT..ATL','NT..PAC','CI','QCSV','PC','IMM','EXM','LI','yld','OU','EX..CALO','EX..PROT','EX..FAT','IM..CALO','IM..PROT','IM..FAT'/;
*
SET aggregQ1(MMM)    'items that can be aggregated by simple summation' 
	/'QP','QC','EX','IM','ST','NT','FO','FE','BF','SWG','CR','VST','AH','LU','QP..SCA','QP..WT','QP..VL','QP..SBE','QP..RT','Qp..RI','QP..OCG','QP..MOL','QP..MA','QP..JA','QP..ARES','QP..FRES','QP..MSW','QP..ECR','POP','QP..PL  ','QP..SL  ','QP..RL  ','QP..SFL ','QP..OVL ','QP..WLF ','QP..OTHW','NT..ATL','NT..PAC','CI','QCSV','PC','IMM','EXM','LI','yld','FL'/;
*
SET BDEX(MMM)    'Biodiesel Exports by feedstocks' 
	/'EX..PL','EX..SL','EX..RL','EX..SFL','EX..OVL','EX..WLF','EX..JA','EX..ECR','EX..ARES','EX..FRES','EX..MSW','EX..OTHW'/;
*
SET BDSD(MMM)    'Biodiesel SDsby feedstocks' 
	/'SD..PL','SD..SL','SD..RL','SD..SFL','SD..OVL','SD..WLF','SD..JA','SD..ECR','SD..ARES','SD..FRES','SD..MSW','SD..OTHW'/;
*
SET BDIM(MMM)    'Biodiesel IMports by feedstocks' 
	/'IM..PL','IM..SL','IM..RL','IM..SFL','IM..OVL','IM..WLF','IM..JA','IM..ECR','IM..ARES','IM..FRES','IM..MSW','IM..OTHW'/;
*
SET BDQC(MMM)    'Biodiesel consumption by feedstocks' 
	/'QC..PL','QC..SL','QC..RL','QC..SFL','QC..OVL','QC..WLF','QC..JA','QC..ECR','QC..ARES','QC..FRES','QC..MSW','QC..OTHW'/;
*
SET BDQP(MMM)    'Biodiesel production by feedstocks' 
	/'QP..PL','QP..SL','QP..RL','QP..SFL','QP..OVL','QP..WLF','QP..JA','QP..ECR','QP..ARES','QP..FRES','QP..MSW','QP..OTHW'/;
*
SET ETEX(MMM)    'Ethanol Exports by feedstocks' 
	/'EX..SBE','EX..SCA','EX..WT','EX..MA','EX..OCG','EX..MOL','EX..RT','EX..RI','EX..ECR','EX..ARES','EX..FRES','EX..MSW','EX..OTHW'/;
*
SET ETSD(MMM)    'Ethanol SDs by feedstocks' 
	/'SD..SBE','SD..SCA','SD..WT','SD..MA','SD..OCG','SD..MOL','SD..RT','SD..RI','SD..ECR','SD..ARES','SD..FRES','SD..MSW','SD..OTHW'/;
*
SET ETIM(MMM)    'Ethanol Imports by feedstocks' 
	/'IM..SBE','IM..SCA','IM..WT','IM..MA','IM..OCG','IM..MOL','IM..RT','IM..RI','IM..ECR','IM..ARES','IM..FRES','IM..MSW','IM..OTHW'/;
*
SET ETQC(MMM)    'Ethanol consumption by feedstocks' 
	/'QC..SBE','QC..SCA','QC..WT','QC..MA','QC..OCG','QC..MOL','QC..RT','QC..RI','QC..ECR','QC..ARES','QC..FRES','QC..MSW','QC..OTHW'/;
*
SET ETFL(MMM)    'Ethanol consumption by feedstocks' 
	/'FL..SBE','FL..SCA','FL..WT','FL..MA','FL..OCG','FL..MOL','FL..RT','FL..RI','FL..ECR','FL..ARES','FL..FRES','FL..MSW','FL..OTHW'/;
*
SET ETQP(MMM)    'Ethanol production by feedstocks' 
	/'QP..SBE','QP..SCA','QP..WT','QP..MA','QP..OCG','QP..MOL','QP..RT','QP..RI','QP..ECR','QP..ARES','QP..FRES','QP..MSW','FL..OTHW'/;
*
SET aggregQmod(MMM)    'items that can be aggregated by simple summation' 
	/'QP','QC','FL','EX','IM','ST','NT','FO','FE','BF','SWG','CR'/;
*
SET GHG(MMM)    'World Emissions' 
	/'GHGWTW','GHGLUC','GHGTOT','GHG..REF'/;
*
SET SAV(MMM)    'Emissions savings' 
	/'GHGWTW..SAV','GHGLUC..SAV','GHGTOT..SAV'/;
*
SET QCm(MMM)    'demand positions' 
	/'FO','FE','SWG','CR','OU','BF'/;
*
SET measures_map(*,MMM)  'maping between single set elemnts and aggregates' /
'MBAL'.('QP','QC','EX','IM','ST','NT','FO','FE','BF','SWG','CR','VST')
*
'AREAS'.('LU','AH','AH2')
*
'cpci_shrs'.('CPCI..SHEN','CPCI..SHFT','CPCI..SHTR','CPCI..SHNT','CPCI..SHSD')
*
'PerCaps'.('FO..PC','FO..PC..CALO','FO..PC..PROT','FO..PC..FAT')
*
'aggregQ'.('QP','QC','EX','IM','ST','NT','FO','FE','BF','SWG','CR','VST','AH','LU','POP','NT..ATL','NT..PAC','CI','QCSV','PC','IMM','EXM','LI','yld','OU','EX..CALO','EX..PROT','EX..FAT','IM..CALO','IM..PROT','IM..FAT')
*
'aggregQ1'.('QP','QC','EX','IM','ST','NT','FO','FE','BF','SWG','CR','VST','AH','LU','QP..SCA','QP..WT','QP..VL','QP..SBE','QP..RT','Qp..RI','QP..OCG','QP..MOL','QP..MA','QP..JA','QP..ARES','QP..FRES','QP..MSW','QP..ECR','POP','QP..PL  ','QP..SL  ','QP..RL  ','QP..SFL ','QP..OVL ','QP..WLF ','QP..OTHW','NT..ATL','NT..PAC','CI','QCSV','PC','IMM','EXM','LI','yld','FL')
*
'BDEX'.('EX..PL','EX..SL','EX..RL','EX..SFL','EX..OVL','EX..WLF','EX..JA','EX..ECR','EX..ARES','EX..FRES','EX..MSW','EX..OTHW')
*
'BDSD'.('SD..PL','SD..SL','SD..RL','SD..SFL','SD..OVL','SD..WLF','SD..JA','SD..ECR','SD..ARES','SD..FRES','SD..MSW','SD..OTHW')
*
'BDIM'.('IM..PL','IM..SL','IM..RL','IM..SFL','IM..OVL','IM..WLF','IM..JA','IM..ECR','IM..ARES','IM..FRES','IM..MSW','IM..OTHW')
*
'BDQC'.('QC..PL','QC..SL','QC..RL','QC..SFL','QC..OVL','QC..WLF','QC..JA','QC..ECR','QC..ARES','QC..FRES','QC..MSW','QC..OTHW')
*
'BDQP'.('QP..PL','QP..SL','QP..RL','QP..SFL','QP..OVL','QP..WLF','QP..JA','QP..ECR','QP..ARES','QP..FRES','QP..MSW','QP..OTHW')
*
'ETEX'.('EX..SBE','EX..SCA','EX..WT','EX..MA','EX..OCG','EX..MOL','EX..RT','EX..RI','EX..ECR','EX..ARES','EX..FRES','EX..MSW','EX..OTHW')
*
'ETSD'.('SD..SBE','SD..SCA','SD..WT','SD..MA','SD..OCG','SD..MOL','SD..RT','SD..RI','SD..ECR','SD..ARES','SD..FRES','SD..MSW','SD..OTHW')
*
'ETIM'.('IM..SBE','IM..SCA','IM..WT','IM..MA','IM..OCG','IM..MOL','IM..RT','IM..RI','IM..ECR','IM..ARES','IM..FRES','IM..MSW','IM..OTHW')
*
'ETQC'.('QC..SBE','QC..SCA','QC..WT','QC..MA','QC..OCG','QC..MOL','QC..RT','QC..RI','QC..ECR','QC..ARES','QC..FRES','QC..MSW','QC..OTHW')
*
'ETFL'.('FL..SBE','FL..SCA','FL..WT','FL..MA','FL..OCG','FL..MOL','FL..RT','FL..RI','FL..ECR','FL..ARES','FL..FRES','FL..MSW','FL..OTHW')
*
'ETQP'.('QP..SBE','QP..SCA','QP..WT','QP..MA','QP..OCG','QP..MOL','QP..RT','QP..RI','QP..ECR','QP..ARES','QP..FRES','QP..MSW','FL..OTHW')
*
'aggregQmod'.('QP','QC','FL','EX','IM','ST','NT','FO','FE','BF','SWG','CR')
*
'GHG'.('GHGWTW','GHGLUC','GHGTOT','GHG..REF')
*
'SAV'.('GHGWTW..SAV','GHGLUC..SAV','GHGTOT..SAV')
*
'QC'.('FO','FE','SWG','CR','OU','BF')
*
/;
SET III    'All ISO regaional codes parent set' /
'ARM'	'        Armenia  '
'AFG'	'        Afghanistan       '
'ALB'	'        Albania  '
'DZA'	'        Algeria  '
'ASM'	'        American Samoa    '
'AND'	'        Andorra  '
'AGO'	'        Angola   '
'ATG'	'        Antigua and Barbuda        '
'ARG'	'        Argentina         '
'AUS'	'        Australia         '
'AUT'	'        Austria  '
'BHS'	'        Bahamas  '
'BHR'	'        Bahrain  '
'BRB'	'        Barbados '
'BLX'	'        Belgium-Luxembourg         '
'BGD'	'        Bangladesh        '
'BMU'	'        Bermuda  '
'BTN'	'        Bhutan   '
'BOL'	'        Bolivia (Plurinational State of)    '
'BWA'	'        Botswana '
'BRA'	'        Brazil   '
'ABW'	'        Aruba    '
'BLZ'	'        Belize   '
'SLB'	'        Solomon Islands   '
'BRN'	'        Brunei Darussalam '
'BGR'	'        Bulgaria '
'MMR'	'        Myanmar  '
'BDI'	'        Burundi  '
'CMR'	'        Cameroon '
'CAN'	'        Canada   '
'CPV'	'        Cape Verde        '
'CYM'	'        Cayman Islands    '
'CAF'	'        Central African Republic   '
'LKA'	'        Sri Lanka         '
'TCD'	'        Chad     '
'CHL'	'        Chile    '
'CHN'	'        China, mainland   '
'COL'	'        Colombia '
'COM'	'        Comoros  '
'COG'	'        Congo    '
'COK'	'        Cook Islands      '
'CRI'	'        Costa Rica        '
'CUB'	'        Cuba     '
'CYP'	'        Cyprus   '
'CZ2'	'        Czechoslovakia    '
'AZE'	'        Azerbaijan        '
'BEN'	'        Benin    '
'DNK'	'        Denmark  '
'DMA'	'        Dominica '
'DOM'	'        Dominican Republic         '
'BLR'	'        Belarus  '
'ECU'	'        Ecuador  '
'EGY'	'        Egypt    '
'SLV'	'        El Salvador       '
'GNQ'	'        Equatorial Guinea '
'ET2'	'        Ethiopia PDR      '
'EST'	'        Estonia  '
'FRO'	'        Faroe Islands     '
'FLK'	'        Falkland Islands (Malvinas)         '
'FJI'	'        Fiji     '
'FIN'	'        Finland  '
'FRA'	'        France   '
'GUF'	'        French Guiana     '
'PYF'	'        French Polynesia  '
'DJI'	'        Djibouti '
'GEO'	'        Georgia  '
'GAB'	'        Gabon    '
'GMB'	'        Gambia   '
'GZA'	'        Gaza strip        '
'DEU'	'        Germany  '
'BIH'	'        Bosnia and Herzegovina     '
'GHA'	'        Ghana    '
'GIB'	'        Gibraltar         '
'KIR'	'        Kiribati '
'GRC'	'        Greece   '
'GRL'	'        Greenland         '
'GRD'	'        Grenada  '
'GLP'	'        Guadeloupe        '
'GUM'	'        Guam     '
'GTM'	'        Guatemala         '
'GIN'	'        Guinea   '
'GUY'	'        Guyana   '
'HTI'	'        Haiti    '
'VAT'	'        Holy See '
'HND'	'        Honduras '
'HKG'	'        China, Hong Kong SAR       '
'HUN'	'        Hungary  '
'HRV'	'        Croatia  '
'ISL'	'        Iceland  '
'IND'	'        India    '
'IDN'	'        Indonesia         '
'IRN'	'        Iran (Islamic Republic of) '
'IRQ'	'        Iraq     '
'IRL'	'        Ireland  '
'ISR'	'        Israel   '
'ITA'	'        Italy    '
'CIV'	'        Cote d Ivoire     '
'KAZ'	'        Kazakhstan        '
'JAM'	'        Jamaica  '
'JPN'	'        Japan    '
'JOR'	'        Jordan   '
'KGZ'	'        Kyrgyzstan        '
'KEN'	'        Kenya    '
'KHM'	'        Cambodia '
'PRK'	'        Democratic Peoples Republic of Korea        '
'KOR'	'        Republic of Korea '
'KWT'	'        Kuwait   '
'LVA'	'        Latvia   '
'LAO'	'        Lao Peoples Democratic Republic    '
'LBN'	'        Lebanon  '
'LSO'	'        Lesotho  '
'LBR'	'        Liberia  '
'LBY'	'        Libyan Arab Jamahiriya     '
'LIE'	'        Liechtenstein     '
'LTU'	'        Lithuania         '
'MHL'	'        Marshall Islands  '
'MAC'	'        China, Macao SAR  '
'MDG'	'        Madagascar        '
'MWI'	'        Malawi   '
'MYS'	'        Malaysia '
'MDV'	'        Maldives '
'MLI'	'        Mali     '
'MLT'	'        Malta    '
'MTQ'	'        Martinique        '
'MRT'	'        Mauritania        '
'MUS'	'        Mauritius         '
'MEX'	'        Mexico   '
'MCO'	'        Monaco   '
'MNG'	'        Mongolia '
'MAR'	'        Morocco  '
'MOZ'	'        Mozambique        '
'FSM'	'        Micronesia (Federated States of)    '
'MDA'	'        Republic of Moldova        '
'NAM'	'        Namibia  '
'NRU'	'        Nauru    '
'NPL'	'        Nepal    '
'NLD'	'        Netherlands       '
'ANT'	'        Netherlands Antilles       '
'NCL'	'        New Caledonia     '
'MKD'	'        The former Yugoslav Republic of Macedonia    '
'VUT'	'        Vanuatu  '
'NZL'	'        New Zealand       '
'NIC'	'        Nicaragua         '
'NER'	'        Niger    '
'NGA'	'        Nigeria  '
'NIU'	'        Niue     '
'NFK'	'        Norfolk Island    '
'NOR'	'        Norway   '
'MNP'	'        Northern Mariana Islands   '
'PIT'	'        Pacific Islands Trust Territory     '
'PAK'	'        Pakistan '
'PAN'	'        Panama   '
'CZE'	'        Czech Republic    '
'PNG'	'        Papua New Guinea  '
'PRY'	'        Paraguay '
'PER'	'        Peru     '
'PHL'	'        Philippines       '
'PCN'	'        Pitcairn Islands  '
'POL'	'        Poland   '
'PRT'	'        Portugal '
'GNB'	'        Guinea-Bissau     '
'TLS'	'        Timor-Leste       '
'PRI'	'        Puerto Rico       '
'ERI'	'        Eritrea  '
'QAT'	'        Qatar    '
'PLW'	'        Palau    '
'ZWE'	'        Zimbabwe '
'REU'	'        Réunion  '
'ROU'	'        Romania  '
'RWA'	'        Rwanda   '
'RUS'	'        Russian Federation         '
'SRM'	'        Serbia and Montenegro      '
'SHN'	'        Saint Helena      '
'KNA'	'        Saint Kitts and Nevis      '
'LCA'	'        Saint Lucia       '
'SPM'	'        Saint Pierre and Miquelon  '
'VCT'	'        Saint Vincent and the Grenadines    '
'SMR'	'        San Marino        '
'STP'	'        Sao Tome and Principe      '
'SAU'	'        Saudi Arabia      '
'SEN'	'        Senegal  '
'SSD'	'       Sudan South'
'SYC'	'        Seychelles        '
'SLE'	'        Sierra Leone      '
'SVN'	'        Slovenia '
'SVK'	'        Slovakia '
'SGP'	'        Singapore         '
'SOM'	'        Somalia  '
'ZAF'	'        South Africa      '
'ESP'	'        Spain    '
'ESH'	'        Western Sahara    '
'SDN'	'        Sudan    '
'SUR'	'        Suriname '
'TJK'	'        Tajikistan        '
'SWZ'	'        Swaziland         '
'SWE'	'        Sweden   '
'CHE'	'        Switzerland       '
'SYR'	'        Syrian Arab Republic       '
'TKM'	'        Turkmenistan      '
'TWN'	'        China, Taiwan Province of  '
'TZA'	'        United Republic of Tanzania         '
'THA'	'        Thailand '
'TGO'	'        Togo     '
'TKL'	'        Tokelau  '
'TON'	'        Tonga    '
'TTO'	'        Trinidad and Tobago        '
'OMN'	'        Oman     '
'TUN'	'        Tunisia  '
'TUR'	'        Turkey   '
'TCA'	'        Turks and Caicos Islands   '
'ARE'	'        United Arab Emirates       '
'UGA'	'        Uganda   '
'TUV'	'        Tuvalu   '
'USR'	'        USSR     '
'GBR'	'        United Kingdom    '
'UKR'	'        Ukraine  '
'USA'	'        United States of America   '
'BFA'	'        Burkina Faso      '
'URY'	'        Uruguay  '
'UZB'	'        Uzbekistan        '
'VEN'	'        Venezuela (Bolivarian Republic of)  '
'VNM'	'        Viet Nam '
'ETH'	'        Ethiopia '
'VGB'	'        British Virgin Islands     '
'VIR'	'        United States Virgin Islands        '
'WLF'	'        Wallis and Futuna Islands  '
'WSM'	'        Samoa    '
'YUG'	'        Yugoslav SFR      '
'YEM'	'        Yemen    '
'COD'	'        Democratic Republic of the Congo    '
'ZMB'	'        Zambia   '
'BEL'	'        Belgium  '
'LUX'	'        Luxembourg        '
'AIA'	'        Anguilla '
'CHS'	'        Channel Islands   '
'SJM'	'        Svalbard and Jan Mayen Islands      '
'IMN'	'        Isle of Man       '
'MYT'	'        Mayotte  '
'SRB'	'        Serbia   '
'MNE'	'        Montenegro        '
'PSE'	'        Occupied Palestinian Territory      '
'AFL'	'        LDC Subsaharan Africa'
'AFS'	'        non LDC Subsaharan Africa'
'AFN'	'       Other North Africa'
'GUL'	'       Gulf states'
'MSR'	'       Other Mashreq'
'SAC'	'       Other Central, South America and Caribbean'
'ASA'	'       Other Asia'
'ASL'	'       LDC Asia'
'OCE'	'       Other Oceania'
'ASC'	'       Other Central Asia'
'EUE'	'       Other Europe'
'AF1'	''
'AF2'	''
'AS2'	''
'NRE'	''
'ASD'	''
'OCE17'	''
'OCL'	''
'EUW'	''
'eue17'	''
'ASA17'	''
'ASD17'	''
'SAC17'	''
/;
*
SET AFL(III)    'LDC Subsaharan Africa' 
	/'BFA','BDI','BEN','COM','DJI','MDG','MWI','ERI','RWA','SOM','UGA','LSO','AGO','CAF','TCD','COD','STP','GMB','GIN','LBR','MLI','NER','GNB','SEN','SLE','TGO','MOZ','SSD','ZMB','TZA'/;
*
SET AFS(III)    'non LDC Subsaharan Africa' 
	/'CIV','SHN','BWA','NAM','SWZ','CPV','CMR','COG','GAB','GHA','KEN','MUS','ZWE','REU','SYC','MYT','ESH','GNQ'/;
*
SET AFN(III)    'Other North Africa' 
	/'MRT','SDN'/;
*
SET GUL(III)    'Gulf states' 
	/'BHR','ARE','KWT','OMN','QAT'/;
*
SET MSR(III)    'Other Mashreq' 
	/'SYR','PSE','IRQ'/;
*
SET SAC(III)    'Other Central, South America and Caribbean' 
	/'HTI','PER','URY','BOL','ECU','FLK','GUF','GUY','SUR','VEN','ATG','BHS','BRB','ABW','BLZ','CYM','CRI','CUB','DMA','DOM','SLV','GRD','GLP','GTM','HND','JAM','MTQ','MSR','ANT','NIC','PAN','PRI','KNA','LCA','VCT','TTO','TCA','VGB','VIR','AIA'/;
*
SET ASA(III)    'Other Asia' 
	/'HKG','MAC','MNG','SGP','TWN','PRK','LKA','BRN','MDV'/;
*
SET ASL(III)    'LDC Asia' 
	/'AFG','BGD','BTN','MMR','KHM','LAO','NPL','TLS'/;
*
SET OCE(III)    'Other Oceania' 
	/'ASM','COK','FJI','PYF','GUM','MHL','FSM','NRU','NCL','NIU','NFK','MNP','PNG','PCN','PIT','PLW','TKL','TON','WLF','WSM','SLB','KIR','VUT','TUV'/;
*
SET ASC(III)    'Other Central Asia' 
	/'ARM','AZE','GEO','KGZ','TJK','TKM','UZB'/;
*
SET EUE(III)    'Other Europe' 
	/'ALB','BIH','MKD','SRB','SRM','MNE','BLR','MDA','AND','FRO','GIB','VAT','ISL','MCO','SMR'/;
*
SET COSC2018(III)    'Cosimo regions 2018' 
	/'AFL','AFS','ETH','NGA','ZAF','AFN','DZA','EGY','GUL','IRN','JOR','LBN','LBY','MAR','MSR','SAU','TUN','YEM','CHL','COL','PRY','SAC','ASA','ASL','IDN','IND','MYS','OCE','PAK','PHL','THA','VNM','ASC','EUE','ISR','KAZ','TUR','UKR'/;
*
SET COSC2017(III)    'Cosimo regions 2017' 
	/'AGO','BFA','CIV','CMR','COD','COG','ETH','GAB','GHA','KEN','MDG','MLI','MOZ','MWI','NGA','RWA','SDN','SEN','SOM','TCD','TZA','UGA','ZAF','ZMB','ZWE','AF1','AF2','DZA','EGY','IRN','IRQ','LBN','LBY','MAR','MRT','TUN','YEM','NRE','SAU','CHL','COL','HTI','PER','PRY','URY','SAC','BGD','IDN','IND','KHM','LAO','MMR','MYS','PAK','PHL','THA','VNM','OCE','OCL','ASD','ASA','AS2','ISR','KAZ','TUR','UKR','EUW','EUE'/;
*
SET AF1(III)    'Other Africa' 
	/'BWA','CPV','MUS','MYT','NAM','SHN','SYC','SWZ','ESH'/;
*
SET AF2(III)    'Other Africa LDC' 
	/'BEN','BDI','CAF','COM','DJI','GNQ','ERI','GMB','GIN','GNB','LSO','LBR','NER','STP','SLE','TGO'/;
*
SET AS2(III)    'Other Asia' 
	/'AFG','BTN','NPL','TLS'/;
*
SET NRE(III)    'Other Near East' 
	/'BHR','JOR','KWT','QAT','SYR','ARE','OMN','PSE'/;
*
SET ISOcodes_map(*,III)  'maping between single set elemnts and aggregates' /
'AFL'.('BFA','BDI','BEN','COM','DJI','MDG','MWI','ERI','RWA','SOM','UGA','LSO','AGO','CAF','TCD','COD','STP','GMB','GIN','LBR','MLI','NER','GNB','SEN','SLE','TGO','MOZ','SSD','ZMB','TZA')
*
'AFS'.('CIV','SHN','BWA','NAM','SWZ','CPV','CMR','COG','GAB','GHA','KEN','MUS','ZWE','REU','SYC','MYT','ESH','GNQ')
*
'AFN'.('MRT','SDN')
*
'GUL'.('BHR','ARE','KWT','OMN','QAT')
*
'MSR'.('SYR','PSE','IRQ')
*
'SAC'.('HTI','PER','URY','BOL','ECU','FLK','GUF','GUY','SUR','VEN','ATG','BHS','BRB','ABW','BLZ','CYM','CRI','CUB','DMA','DOM','SLV','GRD','GLP','GTM','HND','JAM','MTQ','MSR','ANT','NIC','PAN','PRI','KNA','LCA','VCT','TTO','TCA','VGB','VIR','AIA')
*
'ASA'.('HKG','MAC','MNG','SGP','TWN','PRK','LKA','BRN','MDV')
*
'ASL'.('AFG','BGD','BTN','MMR','KHM','LAO','NPL','TLS')
*
'OCE'.('ASM','COK','FJI','PYF','GUM','MHL','FSM','NRU','NCL','NIU','NFK','MNP','PNG','PCN','PIT','PLW','TKL','TON','WLF','WSM','SLB','KIR','VUT','TUV')
*
'ASC'.('ARM','AZE','GEO','KGZ','TJK','TKM','UZB')
*
'EUE'.('ALB','BIH','MKD','SRB','SRM','MNE','BLR','MDA','AND','FRO','GIB','VAT','ISL','MCO','SMR')
*
'COSC2018'.('AFL','AFS','ETH','NGA','ZAF','AFN','DZA','EGY','GUL','IRN','JOR','LBN','LBY','MAR','MSR','SAU','TUN','YEM','CHL','COL','PRY','SAC','ASA','ASL','IDN','IND','MYS','OCE','PAK','PHL','THA','VNM','ASC','EUE','ISR','KAZ','TUR','UKR')
*
'COSC2017'.('AGO','BFA','CIV','CMR','COD','COG','ETH','GAB','GHA','KEN','MDG','MLI','MOZ','MWI','NGA','RWA','SDN','SEN','SOM','TCD','TZA','UGA','ZAF','ZMB','ZWE','AF1','AF2','DZA','EGY','IRN','IRQ','LBN','LBY','MAR','MRT','TUN','YEM','NRE','SAU','CHL','COL','HTI','PER','PRY','URY','SAC','BGD','IDN','IND','KHM','LAO','MMR','MYS','PAK','PHL','THA','VNM','OCE','OCL','ASD','ASA','AS2','ISR','KAZ','TUR','UKR','EUW','EUE')
*
'AF1'.('BWA','CPV','MUS','MYT','NAM','SHN','SYC','SWZ','ESH')
*
'AF2'.('BEN','BDI','CAF','COM','DJI','GNQ','ERI','GMB','GIN','GNB','LSO','LBR','NER','STP','SLE','TGO')
*
'AS2'.('AFG','BTN','NPL','TLS')
*
'NRE'.('BHR','JOR','KWT','QAT','SYR','ARE','OMN','PSE')
*
'ASD'.('ARM','AZE','GEO','KGZ','TJK','TKM','UZB')
*
'OCE17'.('ASM','COK','FJI','PYF','GUM','MHL','FSM','NRU','NCL','NIU','NFK','MNP','PIT','PNG','PCN','PLW','TKL','TON','WLF')
*
'OCL'.('SLB','KIR','VUT','TUV','WSM')
*
'EUW'.('AND','FRO','GIB','GRL','ISL','LIE','SMR','CHS','IMN')
*
'eue17'.('ALB','BLR','BIH','HRV','MDA','MKD','SRM','SRB','MNE')
*
'ASA17'.('BRN','LKA','PRK','MDV','MNG','SGP')
*
'ASD17'.('ARM','AZE','GEO','KGZ','TJK','TKM','UZB')
*
'SAC17'.('SUR','ATG','BHS','BRB','BMU','BOL','ABW','BLZ','CYM','CRI','CUB','DMA','DOM','ECU','SLV','FLK','GUF','GRD','GLP','GTM','GUY','HND','JAM','MTQ','MSR','ANT','NIC','PAN','PRI','KNA','LCA','SPM','VCT','TTO','TCA','VEN','VGB','VIR','AIA')
*
'CosAgg'.('AFL','AFS','AFN','GUL','MSR','SAC','ASA','ASL','OCE','ASC','EUE')
*
'CosAgg17'.('AF1','AF2','AS2','NRE','ASD','OCE17','OCL','EUW','eue17','ASA17','ASD17','SAC17')
*
'E15'.('AUT','DNK','FIN','FRA','DEU','GRC','IRL','ITA','NLD','PRT','ESP','SWE','GBR','BEL','LUX')
*
'NMS'.('BGR','CYP','EST','HUN','LVA','LTU','MLT','CZE','POL','ROU','SVN','SVK')
*
/;
SET FAOREG    'FAOSTAT regional Codes' /
'1'	'Armenia'
'2'	'Afghanistan'
'3'	'Albania'
'4'	'Algeria'
'5'	'American Samoa'
'6'	'Andorra'
'7'	'Angola'
'8'	'Antigua and Barbuda'
'9'	'Argentina'
'10'	'Australia'
'11'	'Austria'
'12'	'Bahamas'
'13'	'Bahrain'
'14'	'Barbados'
'15'	'Belgium-Luxembourg'
'16'	'Bangladesh'
'17'	'Bermuda'
'18'	'Bhutan'
'19'	'Bolivia (Plurinational State of)'
'20'	'Botswana'
'21'	'Brazil'
'22'	'Aruba'
'23'	'Belize'
'25'	'Solomon Islands'
'26'	'Brunei Darussalam'
'27'	'Bulgaria'
'28'	'Myanmar'
'29'	'Burundi'
'32'	'Cameroon'
'33'	'Canada'
'35'	'Cabo Verde'
'36'	'Cayman Islands'
'37'	'Central African Republic'
'38'	'Sri Lanka'
'39'	'Chad'
'40'	'Chile'
'41'	'China, mainland'
'44'	'Colombia'
'45'	'Comoros'
'46'	'Congo'
'47'	'Cook Islands'
'48'	'Costa Rica'
'49'	'Cuba'
'50'	'Cyprus'
'51'	'Czechoslovakia'
'52'	'Azerbaijan'
'53'	'Benin'
'54'	'Denmark'
'55'	'Dominica'
'56'	'Dominican Republic'
'57'	'Belarus'
'58'	'Ecuador'
'59'	'Egypt'
'60'	'El Salvador'
'61'	'Equatorial Guinea'
'62'	'Ethiopia PDR'
'63'	'Estonia'
'64'	'Faroe Islands'
'65'	'Falkland Islands (Malvinas)'
'66'	'Fiji'
'67'	'Finland'
'68'	'France'
'69'	'French Guiana'
'70'	'French Polynesia'
'72'	'Djibouti'
'73'	'Georgia'
'74'	'Gabon'
'75'	'Gambia'
'76'	'Gaza strip'
'79'	'Germany'
'80'	'Bosnia and Herzegovina'
'81'	'Ghana'
'82'	'Gibraltar'
'83'	'Kiribati'
'84'	'Greece'
'85'	'Greenland'
'86'	'Grenada'
'87'	'Guadeloupe'
'88'	'Guam'
'89'	'Guatemala'
'90'	'Guinea'
'91'	'Guyana'
'93'	'Haiti'
'94'	'Vatican'
'95'	'Honduras'
'96'	'China, Hong Kong SAR'
'97'	'Hungary'
'98'	'Croatia'
'99'	'Iceland'
'100'	'India'
'101'	'Indonesia'
'102'	'Iran (Islamic Republic of)'
'103'	'Iraq'
'104'	'Ireland'
'105'	'Israel'
'106'	'Italy'
'107'	'Côte d`Ivoire'
'108'	'Kazakhstan'
'109'	'Jamaica'
'110'	'Japan'
'112'	'Jordan'
'113'	'Kyrgyzstan'
'114'	'Kenya'
'115'	'Cambodia'
'116'	'Democratic People`s Republic of Korea'
'117'	'Republic of Korea'
'118'	'Kuwait'
'119'	'Latvia'
'120'	'Lao People`s Democratic Republic'
'121'	'Lebanon'
'122'	'Lesotho'
'123'	'Liberia'
'124'	'Libya'
'125'	'Liechtenstein'
'126'	'Lithuania'
'127'	'Marshall Islands'
'128'	'China, Macao SAR'
'129'	'Madagascar'
'130'	'Malawi'
'131'	'Malaysia'
'132'	'Maldives'
'133'	'Mali'
'134'	'Malta'
'135'	'Martinique'
'136'	'Mauritania'
'137'	'Mauritius'
'138'	'Mexico'
'140'	'Monaco'
'141'	'Mongolia'
'142'	'Montserrat'
'143'	'Morocco'
'144'	'Mozambique'
'145'	'Micronesia (Federated States of)'
'146'	'Republic of Moldova'
'147'	'Namibia'
'148'	'Nauru'
'149'	'Nepal'
'150'	'Netherlands'
'151'	'Netherlands Antilles'
'153'	'New Caledonia'
'154'	'The former Yugoslav Republic of Macedonia'
'155'	'Vanuatu'
'156'	'New Zealand'
'157'	'Nicaragua'
'158'	'Niger'
'159'	'Nigeria'
'160'	'Niue'
'161'	'Norfolk Island'
'162'	'Norway'
'163'	'Northern Mariana Islands'
'164'	'Pacific Islands Trust Territory'
'165'	'Pakistan'
'166'	'Panama'
'167'	'Czech Republic'
'168'	'Papua New Guinea'
'169'	'Paraguay'
'170'	'Peru'
'171'	'Philippines'
'172'	'Pitcairn Islands'
'173'	'Poland'
'174'	'Portugal'
'175'	'Guinea-Bissau'
'176'	'Timor-Leste'
'177'	'Puerto Rico'
'178'	'Eritrea'
'179'	'Qatar'
'180'	'Palau'
'181'	'Zimbabwe'
'182'	'Réunion'
'183'	'Romania'
'184'	'Rwanda'
'185'	'Russian Federation'
'186'	'Serbia and Montenegro'
'187'	'Saint Helena, Ascension and Tristan da Cunha'
'188'	'Saint Kitts and Nevis'
'189'	'Saint Lucia'
'190'	'Saint Pierre and Miquelon'
'191'	'Saint Vincent and the Grenadines'
'192'	'San Marino'
'193'	'Sao Tome and Principe'
'194'	'Saudi Arabia'
'195'	'Senegal'
'196'	'Seychelles'
'197'	'Sierra Leone'
'198'	'Slovenia'
'199'	'Slovakia'
'200'	'Singapore'
'201'	'Somalia'
'202'	'South Africa'
'203'	'Spain'
'205'	'Western Sahara'
'206'	'Sudan (former)'
'207'	'Suriname'
'208'	'Tajikistan'
'209'	'Swaziland'
'210'	'Sweden'
'211'	'Switzerland'
'212'	'Syrian Arab Republic'
'213'	'Turkmenistan'
'214'	'China, Taiwan Province of'
'215'	'United Republic of Tanzania'
'216'	'Thailand'
'217'	'Togo'
'218'	'Tokelau'
'219'	'Tonga'
'220'	'Trinidad and Tobago'
'221'	'Oman'
'222'	'Tunisia'
'223'	'Turkey'
'224'	'Turks and Caicos Islands'
'225'	'United Arab Emirates'
'226'	'Uganda'
'227'	'Tuvalu'
'228'	'USSR'
'229'	'United Kingdom'
'230'	'Ukraine'
'231'	'United States of America'
'233'	'Burkina Faso'
'234'	'Uruguay'
'235'	'Uzbekistan'
'236'	'Venezuela (Bolivarian Republic of)'
'237'	'Viet Nam'
'238'	'Ethiopia'
'239'	'British Virgin Islands'
'240'	'United States Virgin Islands'
'243'	'Wallis and Futuna Islands'
'244'	'Samoa'
'248'	'Yugoslav SFR'
'249'	'Yemen'
'250'	'Democratic Republic of the Congo'
'251'	'Zambia'
'255'	'Belgium'
'256'	'Luxembourg'
'258'	'Anguilla'
'259'	'Channel Islands'
'260'	'Svalbard and Jan Mayen Islands      '
'264'	'Isle of Man'
'270'	'Mayotte'
'272'	'Serbia'
'273'	'Montenegro'
'276'	'Sudan'
'277'	'South Sudan'
'299'	'Occupied Palestinian Territory'
'351'	'China'
/;
*
SET ISOREG(III)    'ISO regional codes' /
'ARM'	'        Armenia  '
'AFG'	'        Afghanistan       '
'ALB'	'        Albania  '
'DZA'	'        Algeria  '
'ASM'	'        American Samoa    '
'AND'	'        Andorra  '
'AGO'	'        Angola   '
'ATG'	'        Antigua and Barbuda        '
'ARG'	'        Argentina         '
'AUS'	'        Australia         '
'AUT'	'        Austria  '
'BHS'	'        Bahamas  '
'BHR'	'        Bahrain  '
'BRB'	'        Barbados '
'BLX'	'        Belgium-Luxembourg         '
'BGD'	'        Bangladesh        '
'BMU'	'        Bermuda  '
'BTN'	'        Bhutan   '
'BOL'	'        Bolivia (Plurinational State of)    '
'BWA'	'        Botswana '
'BRA'	'        Brazil   '
'ABW'	'        Aruba    '
'BLZ'	'        Belize   '
'SLB'	'        Solomon Islands   '
'BRN'	'        Brunei Darussalam '
'BGR'	'        Bulgaria '
'MMR'	'        Myanmar  '
'BDI'	'        Burundi  '
'CMR'	'        Cameroon '
'CAN'	'        Canada   '
'CPV'	'        Cape Verde        '
'CYM'	'        Cayman Islands    '
'CAF'	'        Central African Republic   '
'LKA'	'        Sri Lanka         '
'TCD'	'        Chad     '
'CHL'	'        Chile    '
'CHN'	'        China, mainland   '
'COL'	'        Colombia '
'COM'	'        Comoros  '
'COG'	'        Congo    '
'COK'	'        Cook Islands      '
'CRI'	'        Costa Rica        '
'CUB'	'        Cuba     '
'CYP'	'        Cyprus   '
'CZ2'	'        Czechoslovakia    '
'AZE'	'        Azerbaijan        '
'BEN'	'        Benin    '
'DNK'	'        Denmark  '
'DMA'	'        Dominica '
'DOM'	'        Dominican Republic         '
'BLR'	'        Belarus  '
'ECU'	'        Ecuador  '
'EGY'	'        Egypt    '
'SLV'	'        El Salvador       '
'GNQ'	'        Equatorial Guinea '
'ET2'	'        Ethiopia PDR      '
'EST'	'        Estonia  '
'FRO'	'        Faroe Islands     '
'FLK'	'        Falkland Islands (Malvinas)         '
'FJI'	'        Fiji     '
'FIN'	'        Finland  '
'FRA'	'        France   '
'GUF'	'        French Guiana     '
'PYF'	'        French Polynesia  '
'DJI'	'        Djibouti '
'GEO'	'        Georgia  '
'GAB'	'        Gabon    '
'GMB'	'        Gambia   '
'GZA'	'        Gaza strip        '
'DEU'	'        Germany  '
'BIH'	'        Bosnia and Herzegovina     '
'GHA'	'        Ghana    '
'GIB'	'        Gibraltar         '
'KIR'	'        Kiribati '
'GRC'	'        Greece   '
'GRL'	'        Greenland         '
'GRD'	'        Grenada  '
'GLP'	'        Guadeloupe        '
'GUM'	'        Guam     '
'GTM'	'        Guatemala         '
'GIN'	'        Guinea   '
'GUY'	'        Guyana   '
'HTI'	'        Haiti    '
'VAT'	'        Holy See '
'HND'	'        Honduras '
'HKG'	'        China, Hong Kong SAR       '
'HUN'	'        Hungary  '
'HRV'	'        Croatia  '
'ISL'	'        Iceland  '
'IND'	'        India    '
'IDN'	'        Indonesia         '
'IRN'	'        Iran (Islamic Republic of) '
'IRQ'	'        Iraq     '
'IRL'	'        Ireland  '
'ISR'	'        Israel   '
'ITA'	'        Italy    '
'CIV'	'        Côte dIvoire     '
'KAZ'	'        Kazakhstan        '
'JAM'	'        Jamaica  '
'JPN'	'        Japan    '
'JOR'	'        Jordan   '
'KGZ'	'        Kyrgyzstan        '
'KEN'	'        Kenya    '
'KHM'	'        Cambodia '
'PRK'	'        Democratic Peoples Republic of Korea        '
'KOR'	'        Republic of Korea '
'KWT'	'        Kuwait   '
'LVA'	'        Latvia   '
'LAO'	'        Lao Peoples Democratic Republic    '
'LBN'	'        Lebanon  '
'LSO'	'        Lesotho  '
'LBR'	'        Liberia  '
'LBY'	'        Libyan Arab Jamahiriya     '
'LIE'	'        Liechtenstein     '
'LTU'	'        Lithuania         '
'MHL'	'        Marshall Islands  '
'MAC'	'        China, Macao SAR  '
'MDG'	'        Madagascar        '
'MWI'	'        Malawi   '
'MYS'	'        Malaysia '
'MDV'	'        Maldives '
'MLI'	'        Mali     '
'MLT'	'        Malta    '
'MTQ'	'        Martinique        '
'MRT'	'        Mauritania        '
'MUS'	'        Mauritius         '
'MEX'	'        Mexico   '
'MCO'	'        Monaco   '
'MNG'	'        Mongolia '
'MSR'	'        Montserrat        '
'MAR'	'        Morocco  '
'MOZ'	'        Mozambique        '
'FSM'	'        Micronesia (Federated States of)    '
'MDA'	'        Republic of Moldova        '
'NAM'	'        Namibia  '
'NRU'	'        Nauru    '
'NPL'	'        Nepal    '
'NLD'	'        Netherlands       '
'ANT'	'        Netherlands Antilles       '
'NCL'	'        New Caledonia     '
'MKD'	'        The former Yugoslav Republic of Macedonia    '
'VUT'	'        Vanuatu  '
'NZL'	'        New Zealand       '
'NIC'	'        Nicaragua         '
'NER'	'        Niger    '
'NGA'	'        Nigeria  '
'NIU'	'        Niue     '
'NFK'	'        Norfolk Island    '
'NOR'	'        Norway   '
'MNP'	'        Northern Mariana Islands   '
'PIT'	'        Pacific Islands Trust Territory     '
'PAK'	'        Pakistan '
'PAN'	'        Panama   '
'CZE'	'        Czech Republic    '
'PNG'	'        Papua New Guinea  '
'PRY'	'        Paraguay '
'PER'	'        Peru     '
'PHL'	'        Philippines       '
'PCN'	'        Pitcairn Islands  '
'POL'	'        Poland   '
'PRT'	'        Portugal '
'GNB'	'        Guinea-Bissau     '
'TLS'	'        Timor-Leste       '
'PRI'	'        Puerto Rico       '
'ERI'	'        Eritrea  '
'QAT'	'        Qatar    '
'PLW'	'        Palau    '
'ZWE'	'        Zimbabwe '
'REU'	'        Réunion  '
'ROU'	'        Romania  '
'RWA'	'        Rwanda   '
'RUS'	'        Russian Federation         '
'SRM'	'        Serbia and Montenegro      '
'SHN'	'        Saint Helena      '
'KNA'	'        Saint Kitts and Nevis      '
'LCA'	'        Saint Lucia       '
'SPM'	'        Saint Pierre and Miquelon  '
'VCT'	'        Saint Vincent and the Grenadines    '
'SMR'	'        San Marino        '
'STP'	'        Sao Tome and Principe      '
'SAU'	'        Saudi Arabia      '
'SEN'	'        Senegal  '
'SYC'	'        Seychelles        '
'SLE'	'        Sierra Leone      '
'SVN'	'        Slovenia '
'SVK'	'        Slovakia '
'SGP'	'        Singapore         '
'SOM'	'        Somalia  '
'ZAF'	'        South Africa      '
'ESP'	'        Spain    '
'ESH'	'        Western Sahara    '
'SDN'	'        Sudan    '
'SUR'	'        Suriname '
'TJK'	'        Tajikistan        '
'SWZ'	'        Swaziland         '
'SWE'	'        Sweden   '
'CHE'	'        Switzerland       '
'SYR'	'        Syrian Arab Republic       '
'TKM'	'        Turkmenistan      '
'TWN'	'        China, Taiwan Province of  '
'TZA'	'        United Republic of Tanzania         '
'THA'	'        Thailand '
'TGO'	'        Togo     '
'TKL'	'        Tokelau  '
'TON'	'        Tonga    '
'TTO'	'        Trinidad and Tobago        '
'OMN'	'        Oman     '
'TUN'	'        Tunisia  '
'TUR'	'        Turkey   '
'TCA'	'        Turks and Caicos Islands   '
'ARE'	'        United Arab Emirates       '
'UGA'	'        Uganda   '
'TUV'	'        Tuvalu   '
'USR'	'        USSR     '
'GBR'	'        United Kingdom    '
'UKR'	'        Ukraine  '
'USA'	'        United States of America   '
'BFA'	'        Burkina Faso      '
'URY'	'        Uruguay  '
'UZB'	'        Uzbekistan        '
'VEN'	'        Venezuela (Bolivarian Republic of)  '
'VNM'	'        Viet Nam '
'ETH'	'        Ethiopia '
'VGB'	'        British Virgin Islands     '
'VIR'	'        United States Virgin Islands        '
'WLF'	'        Wallis and Futuna Islands  '
'WSM'	'        Samoa    '
'YUG'	'        Yugoslav SFR      '
'YEM'	'        Yemen    '
'COD'	'        Democratic Republic of the Congo    '
'ZMB'	'        Zambia   '
'BEL'	'        Belgium  '
'LUX'	'        Luxembourg        '
'AIA'	'        Anguilla '
'CHS'	'        Channel Islands   '
'SJM'	'        Svalbard and Jan Mayen Islands      '
'IMN'	'        Isle of Man       '
'MYT'	'        Mayotte  '
'SRB'	'        Serbia   '
'MNE'	'        Montenegro        '
'PSE'	'        Occupied Palestinian Territory      '
/;
*
SET FAOISOMAP    'mapping to ISO codes' /
'1'.'ARM'
'2'.'AFG'
'3'.'ALB'
'4'.'DZA'
'5'.'ASM'
'6'.'AND'
'7'.'AGO'
'8'.'ATG'
'9'.'ARG'
'10'.'AUS'
'11'.'AUT'
'12'.'BHS'
'13'.'BHR'
'14'.'BRB'
'15'.'BLX'
'16'.'BGD'
'17'.'BMU'
'18'.'BTN'
'19'.'BOL'
'20'.'BWA'
'21'.'BRA'
'22'.'ABW'
'23'.'BLZ'
'25'.'SLB'
'26'.'BRN'
'27'.'BGR'
'28'.'MMR'
'29'.'BDI'
'32'.'CMR'
'33'.'CAN'
'35'.'CPV'
'36'.'CYM'
'37'.'CAF'
'38'.'LKA'
'39'.'TCD'
'40'.'CHL'
'351'.'CHN'
'44'.'COL'
'45'.'COM'
'46'.'COG'
'47'.'COK'
'48'.'CRI'
'49'.'CUB'
'50'.'CYP'
'51'.'CZ2'
'52'.'AZE'
'53'.'BEN'
'54'.'DNK'
'55'.'DMA'
'56'.'DOM'
'57'.'BLR'
'58'.'ECU'
'59'.'EGY'
'60'.'SLV'
'61'.'GNQ'
'62'.'ET2'
'63'.'EST'
'64'.'FRO'
'65'.'FLK'
'66'.'FJI'
'67'.'FIN'
'68'.'FRA'
'69'.'GUF'
'70'.'PYF'
'72'.'DJI'
'73'.'GEO'
'74'.'GAB'
'75'.'GMB'
'76'.'GZA'
'79'.'DEU'
'80'.'BIH'
'81'.'GHA'
'82'.'GIB'
'83'.'KIR'
'84'.'GRC'
'85'.'GRL'
'86'.'GRD'
'87'.'GLP'
'88'.'GUM'
'89'.'GTM'
'90'.'GIN'
'91'.'GUY'
'93'.'HTI'
'94'.'VAT'
'95'.'HND'
'96'.'HKG'
'97'.'HUN'
'98'.'HRV'
'99'.'ISL'
'100'.'IND'
'101'.'IDN'
'102'.'IRN'
'103'.'IRQ'
'104'.'IRL'
'105'.'ISR'
'106'.'ITA'
'107'.'CIV'
'108'.'KAZ'
'109'.'JAM'
'110'.'JPN'
'112'.'JOR'
'113'.'KGZ'
'114'.'KEN'
'115'.'KHM'
'116'.'PRK'
'117'.'KOR'
'118'.'KWT'
'119'.'LVA'
'120'.'LAO'
'121'.'LBN'
'122'.'LSO'
'123'.'LBR'
'124'.'LBY'
'125'.'LIE'
'126'.'LTU'
'127'.'MHL'
'128'.'MAC'
'129'.'MDG'
'130'.'MWI'
'131'.'MYS'
'132'.'MDV'
'133'.'MLI'
'134'.'MLT'
'135'.'MTQ'
'136'.'MRT'
'137'.'MUS'
'138'.'MEX'
'140'.'MCO'
'141'.'MNG'
'142'.'MSR'
'143'.'MAR'
'144'.'MOZ'
'145'.'FSM'
'146'.'MDA'
'147'.'NAM'
'148'.'NRU'
'149'.'NPL'
'150'.'NLD'
'151'.'ANT'
'153'.'NCL'
'154'.'MKD'
'155'.'VUT'
'156'.'NZL'
'157'.'NIC'
'158'.'NER'
'159'.'NGA'
'160'.'NIU'
'161'.'NFK'
'162'.'NOR'
'163'.'MNP'
'164'.'PIT'
'165'.'PAK'
'166'.'PAN'
'167'.'CZE'
'168'.'PNG'
'169'.'PRY'
'170'.'PER'
'171'.'PHL'
'172'.'PCN'
'173'.'POL'
'174'.'PRT'
'175'.'GNB'
'176'.'TLS'
'177'.'PRI'
'178'.'ERI'
'179'.'QAT'
'180'.'PLW'
'181'.'ZWE'
'182'.'REU'
'183'.'ROU'
'184'.'RWA'
'185'.'RUS'
'186'.'SRM'
'187'.'SHN'
'188'.'KNA'
'189'.'LCA'
'190'.'SPM'
'191'.'VCT'
'192'.'SMR'
'193'.'STP'
'194'.'SAU'
'195'.'SEN'
'196'.'SYC'
'197'.'SLE'
'198'.'SVN'
'199'.'SVK'
'200'.'SGP'
'201'.'SOM'
'202'.'ZAF'
'203'.'ESP'
'205'.'ESH'
'206'.'SDN'
'207'.'SUR'
'208'.'TJK'
'209'.'SWZ'
'210'.'SWE'
'211'.'CHE'
'212'.'SYR'
'213'.'TKM'
'214'.'TWN'
'215'.'TZA'
'216'.'THA'
'217'.'TGO'
'218'.'TKL'
'219'.'TON'
'220'.'TTO'
'221'.'OMN'
'222'.'TUN'
'223'.'TUR'
'224'.'TCA'
'225'.'ARE'
'226'.'UGA'
'227'.'TUV'
'228'.'USR'
'229'.'GBR'
'230'.'UKR'
'231'.'USA'
'233'.'BFA'
'234'.'URY'
'235'.'UZB'
'236'.'VEN'
'237'.'VNM'
'238'.'ETH'
'239'.'VGB'
'240'.'VIR'
'243'.'WLF'
'244'.'WSM'
'248'.'YUG'
'249'.'YEM'
'250'.'COD'
'251'.'ZMB'
'255'.'BEL'
'256'.'LUX'
'258'.'AIA'
'259'.'CHS'
'260'.'SJM'
'264'.'IMN'
'270'.'MYT'
'272'.'SRB'
'273'.'MNE'
'299'.'PSE'
'276'.'SDN'
'277'.'SDN'
/;
*
SET UNREG    'UNStats regional codes' /
'4'	'Afghanistan'
'248'	'Åland Islands'
'8'	'Albania'
'12'	'Algeria'
'16'	'American Samoa'
'20'	'Andorra'
'24'	'Angola'
'660'	'Anguilla'
'28'	'Antigua and Barbuda'
'32'	'Argentina'
'51'	'Armenia'
'533'	'Aruba'
'36'	'Australia'
'40'	'Austria'
'31'	'Azerbaijan'
'44'	'Bahamas'
'48'	'Bahrain'
'50'	'Bangladesh'
'52'	'Barbados'
'112'	'Belarus'
'56'	'Belgium'
'84'	'Belize'
'204'	'Benin'
'60'	'Bermuda'
'64'	'Bhutan'
'68'	'Bolivia (Plurinational State of)'
'535'	'Bonaire, Sint Eustatius and Saba'
'70'	'Bosnia and Herzegovina'
'72'	'Botswana'
'76'	'Brazil'
'92'	'British Virgin Islands'
'96'	'Brunei Darussalam'
'100'	'Bulgaria'
'854'	'Burkina Faso'
'108'	'Burundi'
'132'	'Cabo Verde'
'116'	'Cambodia'
'120'	'Cameroon'
'124'	'Canada'
'136'	'Cayman Islands'
'140'	'Central African Republic'
'148'	'Chad'
'830'	'Channel Islands'
'152'	'Chile'
'156'	'China'
'344'	'China, Hong Kong Special Administrative Region'
'446'	'China, Macao Special Administrative Region'
'170'	'Colombia'
'174'	'Comoros'
'178'	'Congo'
'184'	'Cook Islands'
'188'	'Costa Rica'
'384'	'Côte dIvoire'
'191'	'Croatia'
'192'	'Cuba'
'531'	'Curaçao'
'196'	'Cyprus'
'203'	'Czech Republic'
'408'	'Democratic Peoples Republic of Korea'
'180'	'Democratic Republic of the Congo'
'208'	'Denmark'
'262'	'Djibouti'
'212'	'Dominica'
'214'	'Dominican Republic'
'218'	'Ecuador'
'818'	'Egypt'
'222'	'El Salvador'
'226'	'Equatorial Guinea'
'232'	'Eritrea'
'233'	'Estonia'
'231'	'Ethiopia'
'234'	'Faeroe Islands'
'238'	'Falkland Islands (Malvinas)'
'242'	'Fiji'
'246'	'Finland'
'250'	'France'
'254'	'French Guiana'
'258'	'French Polynesia'
'266'	'Gabon'
'270'	'Gambia'
'268'	'Georgia'
'276'	'Germany'
'288'	'Ghana'
'292'	'Gibraltar'
'300'	'Greece'
'304'	'Greenland'
'308'	'Grenada'
'312'	'Guadeloupe'
'316'	'Guam'
'320'	'Guatemala'
'831'	'Guernsey'
'324'	'Guinea'
'624'	'Guinea-Bissau'
'328'	'Guyana'
'332'	'Haiti'
'336'	'Holy See'
'340'	'Honduras'
'348'	'Hungary'
'352'	'Iceland'
'356'	'India'
'360'	'Indonesia'
'364'	'Iran (Islamic Republic of)'
'368'	'Iraq'
'372'	'Ireland'
'833'	'Isle of Man'
'376'	'Israel'
'380'	'Italy'
'388'	'Jamaica'
'392'	'Japan'
'832'	'Jersey'
'400'	'Jordan'
'398'	'Kazakhstan'
'404'	'Kenya'
'296'	'Kiribati'
'414'	'Kuwait'
'417'	'Kyrgyzstan'
'418'	'Lao Peoples Democratic Republic'
'428'	'Latvia'
'422'	'Lebanon'
'426'	'Lesotho'
'430'	'Liberia'
'434'	'Libya'
'438'	'Liechtenstein'
'440'	'Lithuania'
'442'	'Luxembourg'
'450'	'Madagascar'
'454'	'Malawi'
'458'	'Malaysia'
'462'	'Maldives'
'466'	'Mali'
'470'	'Malta'
'584'	'Marshall Islands'
'474'	'Martinique'
'478'	'Mauritania'
'480'	'Mauritius'
'175'	'Mayotte'
'484'	'Mexico'
'583'	'Micronesia (Federated States of)'
'492'	'Monaco'
'496'	'Mongolia'
'499'	'Montenegro'
'500'	'Montserrat'
'504'	'Morocco'
'508'	'Mozambique'
'104'	'Myanmar'
'516'	'Namibia'
'520'	'Nauru'
'524'	'Nepal'
'528'	'Netherlands'
'540'	'New Caledonia'
'554'	'New Zealand'
'558'	'Nicaragua'
'562'	'Niger'
'566'	'Nigeria'
'570'	'Niue'
'574'	'Norfolk Island'
'580'	'Northern Mariana Islands'
'578'	'Norway'
'512'	'Oman'
'586'	'Pakistan'
'585'	'Palau'
'591'	'Panama'
'598'	'Papua New Guinea'
'600'	'Paraguay'
'604'	'Peru'
'608'	'Philippines'
'612'	'Pitcairn'
'616'	'Poland'
'620'	'Portugal'
'630'	'Puerto Rico'
'634'	'Qatar'
'410'	'Republic of Korea'
'498'	'Republic of Moldova'
'638'	'Réunion'
'642'	'Romania'
'643'	'Russian Federation'
'646'	'Rwanda'
'652'	'Saint Barthélemy'
'654'	'Saint Helena'
'659'	'Saint Kitts and Nevis'
'662'	'Saint Lucia'
'663'	'Saint Martin (French part)'
'666'	'Saint Pierre and Miquelon'
'670'	'Saint Vincent and the Grenadines'
'882'	'Samoa'
'674'	'San Marino'
'678'	'Sao Tome and Principe'
'680'	'Sark'
'682'	'Saudi Arabia'
'686'	'Senegal'
'688'	'Serbia'
'690'	'Seychelles'
'694'	'Sierra Leone'
'702'	'Singapore'
'534'	'Sint Maarten (Dutch part)'
'703'	'Slovakia'
'705'	'Slovenia'
'90'	'Solomon Islands'
'706'	'Somalia'
'710'	'South Africa'
'728'	'South Sudan'
'724'	'Spain'
'144'	'Sri Lanka'
'275'	'State of Palestine'
'729'	'Sudan'
'740'	'Suriname'
'744'	'Svalbard and Jan Mayen Islands'
'748'	'Swaziland'
'752'	'Sweden'
'756'	'Switzerland'
'760'	'Syrian Arab Republic'
'762'	'Tajikistan'
'764'	'Thailand'
'807'	'The former Yugoslav Republic of Macedonia'
'626'	'Timor-Leste'
'768'	'Togo'
'772'	'Tokelau'
'776'	'Tonga'
'780'	'Trinidad and Tobago'
'788'	'Tunisia'
'792'	'Turkey'
'795'	'Turkmenistan'
'796'	'Turks and Caicos Islands'
'798'	'Tuvalu'
'800'	'Uganda'
'804'	'Ukraine'
'784'	'United Arab Emirates'
'826'	'United Kingdom of Great Britain and Northern Ireland'
'834'	'United Republic of Tanzania'
'840'	'United States of America'
'850'	'United States Virgin Islands'
'858'	'Uruguay'
'860'	'Uzbekistan'
'548'	'Vanuatu'
'862'	'Venezuela (Bolivarian Republic of)'
'704'	'Viet Nam'
'876'	'Wallis and Futuna Islands'
'732'	'Western Sahara'
'887'	'Yemen'
'894'	'Zambia'
'716'	'Zimbabwe'
/;
*
SET UNISOMAP    'mapping of UNSTATS codes to iso codes' /
'4'.'AFG'
'248'.'ALA'
'8'.'ALB'
'12'.'DZA'
'16'.'ASM'
'20'.'AND'
'24'.'AGO'
'660'.'AIA'
'28'.'ATG'
'32'.'ARG'
'51'.'ARM'
'533'.'ABW'
'36'.'AUS'
'40'.'AUT'
'31'.'AZE'
'44'.'BHS'
'48'.'BHR'
'50'.'BGD'
'52'.'BRB'
'112'.'BLR'
'56'.'BEL'
'84'.'BLZ'
'204'.'BEN'
'60'.'BMU'
'64'.'BTN'
'68'.'BOL'
'535'.'BES'
'70'.'BIH'
'72'.'BWA'
'76'.'BRA'
'92'.'VGB'
'96'.'BRN'
'100'.'BGR'
'854'.'BFA'
'108'.'BDI'
'132'.'CPV'
'116'.'KHM'
'120'.'CMR'
'124'.'CAN'
'136'.'CYM'
'140'.'CAF'
'148'.'TCD'
'830'.''
'152'.'CHL'
'156'.'CHN'
'344'.'HKG'
'446'.'MAC'
'170'.'COL'
'174'.'COM'
'178'.'COG'
'184'.'COK'
'188'.'CRI'
'384'.'CIV'
'191'.'HRV'
'192'.'CUB'
'531'.'CUW'
'196'.'CYP'
'203'.'CZE'
'408'.'PRK'
'180'.'COD'
'208'.'DNK'
'262'.'DJI'
'212'.'DMA'
'214'.'DOM'
'218'.'ECU'
'818'.'EGY'
'222'.'SLV'
'226'.'GNQ'
'232'.'ERI'
'233'.'EST'
'231'.'ETH'
'234'.'FRO'
'238'.'FLK'
'242'.'FJI'
'246'.'FIN'
'250'.'FRA'
'254'.'GUF'
'258'.'PYF'
'266'.'GAB'
'270'.'GMB'
'268'.'GEO'
'276'.'DEU'
'288'.'GHA'
'292'.'GIB'
'300'.'GRC'
'304'.'GRL'
'308'.'GRD'
'312'.'GLP'
'316'.'GUM'
'320'.'GTM'
'831'.'GGY'
'324'.'GIN'
'624'.'GNB'
'328'.'GUY'
'332'.'HTI'
'336'.'VAT'
'340'.'HND'
'348'.'HUN'
'352'.'ISL'
'356'.'IND'
'360'.'IDN'
'364'.'IRN'
'368'.'IRQ'
'372'.'IRL'
'833'.'IMN'
'376'.'ISR'
'380'.'ITA'
'388'.'JAM'
'392'.'JPN'
'832'.'JEY'
'400'.'JOR'
'398'.'KAZ'
'404'.'KEN'
'296'.'KIR'
'414'.'KWT'
'417'.'KGZ'
'418'.'LAO'
'428'.'LVA'
'422'.'LBN'
'426'.'LSO'
'430'.'LBR'
'434'.'LBY'
'438'.'LIE'
'440'.'LTU'
'442'.'LUX'
'450'.'MDG'
'454'.'MWI'
'458'.'MYS'
'462'.'MDV'
'466'.'MLI'
'470'.'MLT'
'584'.'MHL'
'474'.'MTQ'
'478'.'MRT'
'480'.'MUS'
'175'.'MYT'
'484'.'MEX'
'583'.'FSM'
'492'.'MCO'
'496'.'MNG'
'499'.'MNE'
'500'.'MSR'
'504'.'MAR'
'508'.'MOZ'
'104'.'MMR'
'516'.'NAM'
'520'.'NRU'
'524'.'NPL'
'528'.'NLD'
'540'.'NCL'
'554'.'NZL'
'558'.'NIC'
'562'.'NER'
'566'.'NGA'
'570'.'NIU'
'574'.'NFK'
'580'.'MNP'
'578'.'NOR'
'512'.'OMN'
'586'.'PAK'
'585'.'PLW'
'591'.'PAN'
'598'.'PNG'
'600'.'PRY'
'604'.'PER'
'608'.'PHL'
'612'.'PCN'
'616'.'POL'
'620'.'PRT'
'630'.'PRI'
'634'.'QAT'
'410'.'KOR'
'498'.'MDA'
'638'.'REU'
'642'.'ROU'
'643'.'RUS'
'646'.'RWA'
'652'.'BLM'
'654'.'SHN'
'659'.'KNA'
'662'.'LCA'
'663'.'MAF'
'666'.'SPM'
'670'.'VCT'
'882'.'WSM'
'674'.'SMR'
'678'.'STP'
'680'.''
'682'.'SAU'
'686'.'SEN'
'688'.'SRB'
'690'.'SYC'
'694'.'SLE'
'702'.'SGP'
'534'.'SXM'
'703'.'SVK'
'705'.'SVN'
'90'.'SLB'
'706'.'SOM'
'710'.'ZAF'
'728'.'SSD'
'724'.'ESP'
'144'.'LKA'
'275'.'PSE'
'729'.'SDN'
'740'.'SUR'
'744'.'SJM'
'748'.'SWZ'
'752'.'SWE'
'756'.'CHE'
'760'.'SYR'
'762'.'TJK'
'764'.'THA'
'807'.'MKD'
'626'.'TLS'
'768'.'TGO'
'772'.'TKL'
'776'.'TON'
'780'.'TTO'
'788'.'TUN'
'792'.'TUR'
'795'.'TKM'
'796'.'TCA'
'798'.'TUV'
'800'.'UGA'
'804'.'UKR'
'784'.'ARE'
'826'.'GBR'
'834'.'TZA'
'840'.'USA'
'850'.'VIR'
'858'.'URY'
'860'.'UZB'
'548'.'VUT'
'862'.'VEN'
'704'.'VNM'
'876'.'WLF'
'732'.'ESH'
'887'.'YEM'
'894'.'ZMB'
'716'.'ZWE'
/;
*
SET UNAGGREG    'UN aggregate regions' /
'2'	'Africa'
'14'	'Eastern Africa'
'17'	'Middle Africa'
'15'	'Northern Africa'
'18'	'Southern Africa'
'11'	'Western Africa'
'19'	'Americas'
'419'	'Latin America and the Caribbean'
'29'	'Caribbean'
'13'	'Central America'
'5'	'South America'
'21'	'Northern America'
'142'	'Asia'
'143'	'Central Asia'
'30'	'Eastern Asia'
'34'	'Southern Asia'
'35'	'South-Eastern Asia'
'145'	'Western Asia'
'150'	'Europe'
'151'	'Eastern Europe'
'154'	'Northern Europe'
'39'	'Southern Europe'
'155'	'Western Europe'
'9'	'Oceania'
'53'	'Australia and New Zealand'
'54'	'Melanesia'
'57'	'Micronesia'
'61'	'Polynesia'
/;
*
SET UNAGGMAP    'Mapping to UN aggregates' /
'108'.'14'
'174'.'14'
'262'.'14'
'232'.'14'
'231'.'14'
'404'.'14'
'450'.'14'
'454'.'14'
'480'.'14'
'175'.'14'
'508'.'14'
'638'.'14'
'646'.'14'
'690'.'14'
'706'.'14'
'728'.'14'
'800'.'14'
'834'.'14'
'894'.'14'
'716'.'14'
'140'.'17'
'148'.'17'
'178'.'17'
'180'.'17'
'226'.'17'
'266'.'17'
'678'.'17'
'12'.'15'
'818'.'15'
'729'.'15'
'788'.'15'
'732'.'15'
'72'.'18'
'426'.'18'
'516'.'18'
'710'.'18'
'748'.'18'
'204'.'18'
'854'.'18'
'132'.'18'
'384'.'18'
'270'.'11'
'288'.'11'
'324'.'11'
'624'.'11'
'430'.'11'
'466'.'11'
'478'.'11'
'562'.'11'
'566'.'11'
'654'.'11'
'686'.'11'
'694'.'11'
'768'.'11'
'660'.'11'
'28'.'11'
'533'.'11'
'44'.'11'
'52'.'29'
'535'.'29'
'92'.'29'
'136'.'29'
'192'.'29'
'531'.'29'
'212'.'29'
'214'.'29'
'308'.'29'
'312'.'29'
'332'.'29'
'388'.'29'
'474'.'29'
'500'.'29'
'630'.'29'
'652'.'29'
'659'.'29'
'662'.'29'
'663'.'29'
'670'.'29'
'534'.'29'
'780'.'29'
'796'.'29'
'850'.'29'
'84'.'13'
'188'.'13'
'222'.'13'
'320'.'13'
'340'.'13'
'484'.'13'
'558'.'13'
'591'.'13'
'32'.'5'
'68'.'5'
'76'.'5'
'152'.'5'
'170'.'5'
'218'.'5'
'238'.'5'
'254'.'5'
'328'.'5'
'600'.'5'
'604'.'5'
'740'.'5'
'858'.'5'
'862'.'5'
'60'.'21'
'124'.'21'
'304'.'21'
'666'.'21'
'840'.'21'
'398'.'143'
'417'.'143'
'762'.'143'
'795'.'143'
'860'.'143'
'156'.'30'
'344'.'30'
'446'.'30'
'408'.'30'
'392'.'30'
'496'.'30'
'410'.'30'
'4'.'34'
'50'.'34'
'64'.'34'
'356'.'34'
'364'.'34'
'462'.'34'
'524'.'34'
'586'.'34'
'144'.'34'
'96'.'35'
'116'.'35'
'360'.'35'
'418'.'35'
'458'.'35'
'104'.'35'
'608'.'35'
'702'.'35'
'764'.'35'
'626'.'35'
'704'.'35'
'51'.'145'
'31'.'145'
'48'.'145'
'196'.'145'
'268'.'145'
'368'.'145'
'376'.'145'
'400'.'145'
'414'.'145'
'422'.'145'
'512'.'145'
'634'.'145'
'682'.'145'
'275'.'145'
'760'.'145'
'792'.'145'
'784'.'145'
'887'.'145'
'112'.'151'
'100'.'151'
'203'.'151'
'348'.'151'
'616'.'151'
'498'.'151'
'642'.'151'
'643'.'151'
'703'.'151'
'804'.'151'
'248'.'154'
'830'.'154'
'208'.'154'
'233'.'154'
'234'.'154'
'246'.'154'
'831'.'154'
'352'.'154'
'372'.'154'
'833'.'154'
'832'.'154'
'428'.'154'
'440'.'154'
'578'.'154'
'680'.'154'
'744'.'154'
'752'.'154'
'826'.'154'
'8'.'39'
'20'.'39'
'70'.'39'
'191'.'39'
'292'.'39'
'300'.'39'
'336'.'39'
'380'.'39'
'470'.'39'
'499'.'39'
'620'.'39'
'674'.'39'
'688'.'39'
'705'.'39'
'724'.'39'
'807'.'39'
'40'.'155'
'56'.'155'
'250'.'155'
'276'.'155'
'438'.'155'
'442'.'155'
'492'.'155'
'528'.'155'
'756'.'155'
'36'.'53'
'554'.'53'
'574'.'53'
'242'.'54'
'540'.'54'
'598'.'54'
'90'.'54'
'548'.'54'
'316'.'57'
'296'.'57'
'584'.'57'
'583'.'57'
'520'.'57'
'580'.'57'
'585'.'57'
'16'.'61'
'184'.'61'
'258'.'61'
'570'.'61'
'612'.'61'
'882'.'61'
'772'.'61'
'776'.'61'
'798'.'61'
'876'.'61'
'14'.'2'
'17'.'2'
'15'.'2'
'18'.'2'
'11'.'2'
'419'.'19'
'29'.'419'
'13'.'419'
'5'.'419'
'21'.'19'
'143'.'142'
'30'.'142'
'34'.'142'
'35'.'142'
'145'.'142'
'151'.'150'
'154'.'150'
'39'.'150'
'155'.'150'
'53'.'9'
'54'.'9'
'57'.'9'
'61'.'9'
/;
*
